-- =====================================================================
-- C2 — Seed Conseiller V1 : 60 tips de démarrage (10 par catégorie)
-- =====================================================================
-- V1 : tips courts mais solides, sourcés. V2 ajoutera 240 tips supplémentaires.
-- Sources : NRC 2012, INRA 2018, FAO, IFIP, CIRAD, OIE.

insert into tips_conseiller (slug, titre, categorie, niveau, resume, contenu, tags, source) values

-- ========================================================
-- REPRODUCTION (10 tips)
-- ========================================================

('reperer-chaleurs-truie', 'Repérer les chaleurs d''une truie',
 'reproduction', 'debutant',
 'Une truie en chaleur présente vulve rouge gonflée, réflexe d''immobilisation au test du dos, et agitation.',
 E'## Les 3 signes infaillibles\n\n**1. Signes vulvaires** : vulve rouge, gonflée, parfois écoulement clair. Apparaissent 12-24h avant l''ovulation.\n\n**2. Test du dos** : appuyer fermement sur le dos. Si la truie reste **immobile** (oreilles dressées, regard fixe), elle est en chaleur. Le test est plus fiable en présence d''un verrat (effet mâle).\n\n**3. Comportement** : agitation, refus de manger, vocalisations, tentatives de monter ses congénères.\n\n## Fréquence d''observation\n\n- **2 fois par jour minimum** (matin + soir), à heure fixe\n- Idéalement après un contact verrat de 5-10 min\n\n## Quand inséminer ?\n\n- Si chaleur détectée matin → IA le soir + lendemain matin\n- Si chaleur détectée soir → IA le lendemain matin + soir\n- **Double IA à 12h d''intervalle** = taux de fertilité optimal',
 ARRAY['chaleur', 'oestrus', 'truie', 'ia', 'detection'],
 'INRA 2018, IFIP Mémento Porc'),

('cycle-oestral-porcin', 'Cycle œstral porcin : 21 jours',
 'reproduction', 'debutant',
 'Le cycle œstral de la truie dure 21 jours en moyenne. Chaleurs visibles 2-3 jours, ovulation au jour 1-2.',
 E'## Phases du cycle\n\n| Phase | Durée | Caractéristique |\n|---|---|---|\n| Pro-œstrus | 2 jours | Vulve gonfle, pas de réflexe immobilisation |\n| **Œstrus** | **2-3 jours** | **Chaleur visible, ovulation J1-J2** |\n| Métœstrus | 2 jours | Vulve dégonfle |\n| Diœstrus | 14 jours | Repos sexuel |\n\n## Implications pratiques\n\n- Une truie non saillie revient en chaleur **21 jours après**\n- Détection ratée = 21 jours perdus = ~10 porcelets en moins/an\n- **Surveiller J18-J24 post-saillie** : retour en chaleur = échec gestation',
 ARRAY['cycle', 'oestrus', 'physiologie', 'ovulation'],
 'NRC 2012, INRA 2018'),

('ia-porcine-technique', 'Technique IA porcine en 7 étapes',
 'reproduction', 'intermediaire',
 'L''insémination artificielle porcine se fait en 7 étapes : préparation, hygiène, cathéter, dépôt, ocytocine optionnelle, observation.',
 E'## Matériel nécessaire\n\n- Cathéter IA stérile (spirale ou type Melrose)\n- Dose semence tempérée à 17°C (sortie frigo 15 min avant)\n- Gants jetables, lubrifiant non spermicide\n- Eau tiède, papier essuie-tout\n\n## Les 7 étapes\n\n1. **Préparer la truie** : nettoyer la vulve (eau + papier propre)\n2. **Stimulation** : appuyer sur le dos, présence verrat si possible\n3. **Lubrifier** la pointe du cathéter (jamais de gel spermicide)\n4. **Insérer le cathéter** vers le haut puis horizontal, tourner anti-horaire jusqu''au verrouillage cervical (~20-25 cm)\n5. **Visser la dose** sur le cathéter, lever légèrement\n6. **Laisser la truie aspirer** la dose (5-8 min naturellement)\n7. **Retirer le cathéter** doucement, noter dans le carnet (date, heure, verrat, dose)\n\n## Conservation des doses\n\n- À **17°C** (jamais frigo classique 4°C !)\n- Durée : 3-7 jours selon diluant\n- Retourner doucement 1x/jour pour homogénéiser',
 ARRAY['ia', 'insemination', 'technique', 'catheter', 'semence'],
 'IFIP, INRA, CIPAQ'),

('gestation-114-jours', 'Gestation porcine : 3 mois, 3 semaines, 3 jours',
 'reproduction', 'debutant',
 'La gestation dure 114 jours en moyenne (113-115). Date prévue mise-bas = saillie + 114j.',
 E'## Calcul date mise-bas\n\n**Saillie + 114 jours = mise-bas**\n\nMoyen mnémotechnique : **3 mois + 3 semaines + 3 jours**\n\n## Variabilité normale\n\n- 110-118 jours = normal\n- < 110 j = prématuré (risque mortalité porcelets)\n- > 118 j = retard, surveiller\n\n## Diagnostic de gestation\n\n- **21 jours post-saillie** : surveiller retour en chaleur. Pas de chaleur = probable gestation\n- **28-35 jours** : échographie portable confirme à 95%\n- **45+ jours** : palpation rectale (vétérinaire)\n\n## Étapes clés\n\n| Jour | Événement |\n|---|---|\n| J21 | Implantation, surveiller retour chaleur |\n| J35 | Échographie possible |\n| J90 | Transfert maternité, vaccin parvo/rouget |\n| J110 | Préparer la mise-bas |\n| **J114** | **Mise-bas prévue** |',
 ARRAY['gestation', 'date-mise-bas', 'echographie', 'diagnostic'],
 'INRA 2018, IFIP'),

('preparer-mise-bas', 'Préparer une mise-bas en maternité',
 'reproduction', 'intermediaire',
 'Transférer la truie 5-7 jours avant la date prévue, désinfecter, ajuster température à 18-20°C truie / 30-32°C porcelets.',
 E'## J-7 : transfert maternité\n\n- Bâtiment **nettoyé et désinfecté** (vide sanitaire 7j minimum)\n- Caillebotis fonctionnels\n- **Lampe chauffante** au-dessus du nid à porcelets (30-32°C)\n- Auge nettoyée, eau propre\n\n## J-3 : surveillance accrue\n\n- Vérifier descente du lait (mamelles tendues, sécrétion)\n- Truie agitée, fait son nid avec litière\n- **Glaire vulvaire** = mise-bas dans 24-48h\n\n## J0 : pendant la mise-bas\n\n- Durée normale : **3-5h**, intervalle entre porcelets < 30 min\n- Surveiller sans déranger\n- Si > 45 min entre 2 porcelets ou détresse truie → intervenir\n- **Soins porcelets** : sécher, désinfecter cordon (iode), placer sous lampe\n\n## Matériel à portée\n\n- Iode 7%, gants, ciseaux désinfectés\n- Antibiotique de couverture (post-partum)\n- Numéro vétérinaire\n- Lampe + eau chaude (réanimation porcelet froid)',
 ARRAY['mise-bas', 'maternite', 'preparation', 'porcelets'],
 'IFIP, INRA'),

('soins-porcelet-naissance', 'Soins immédiats au porcelet',
 'reproduction', 'debutant',
 'Sécher, désinfecter cordon à l''iode, ferrer si nécessaire, mettre sous lampe à 32°C, faire téter le colostrum dans les 6h.',
 E'## Dans les 5 premières minutes\n\n1. **Sécher** avec un linge ou paille\n2. **Désinfecter le cordon** (iode 7%) à 3 cm du ventre\n3. **Vérifier la respiration** : si faible, dégager les voies (mucus), masser, eau chaude\n4. **Placer sous lampe** chauffante (30-32°C nid porcelet)\n\n## Dans les 6 premières heures\n\n- **Colostrum impératif** : 200-250 g/porcelet sur 24h\n- Le colostrum apporte les anticorps maternels (immunité passive)\n- Mettre les plus faibles aux mamelles avant pour priorité d''accès\n\n## Dans les 24-72h\n\n- **Fer dextran 200 mg IM** (J1-J3) : 1 ml de Fer 100 mg/ml ou 0.5 ml de Fer 200 mg/ml. **NE PAS injecter 2 ml de 200 mg/ml = surdose toxique !**\n- Couper les dents (épointage) si bagarres tétine\n- Couper la queue si caudectomie pratiquée\n\n## J7 : castration des mâles\n\n- Avec antiseptique + méloxicam (anti-inflammatoire)\n- Plaie surveillée 3 jours',
 ARRAY['porcelet', 'naissance', 'colostrum', 'fer', 'castration'],
 'INRA, IFIP, OIE'),

('intervalle-sevrage-saillie', 'Intervalle sevrage-saillie (ISS) : viser 5 jours',
 'reproduction', 'expert',
 'L''ISS optimal est de 4-7 jours. Au-delà de 10 jours, perte de productivité significative.',
 E'## Qu''est-ce que l''ISS ?\n\nL''**Intervalle Sevrage-Saillie** = nombre de jours entre le sevrage des porcelets et la nouvelle saillie de la truie.\n\n## Cibles\n\n- **Excellent** : 4-5 jours\n- **Bon** : 6-7 jours\n- **À surveiller** : 8-12 jours\n- **Mauvais** : > 12 jours\n\n## Pourquoi c''est crucial\n\n- ISS de 5j vs 10j = **0.3 porcelets supplémentaires par truie/an**\n- Sur 20 truies = 6 porcelets/an = ~80 000 FCFA\n\n## Causes d''ISS allongé\n\n1. **Sous-nutrition en lactation** : truies maigres = anœstrus post-sevrage\n2. **Stress thermique** : > 28°C affecte la reprise œstrale\n3. **Première portée** : ISS souvent plus long (jusqu''à 10j)\n4. **Sevrage trop précoce** (< 18j) : utérus non involué\n5. **Pathologie utérine** : métrite\n\n## Solutions\n\n- Truie ad libitum en lactation, eau fraîche\n- Effet verrat dès J2 post-sevrage\n- Flushing énergétique 3-5j (concentré + eau)',
 ARRAY['iss', 'sevrage', 'productivite', 'truie'],
 'IFIP, INRA, BIPORC'),

('synchronisation-chaleurs', 'Synchronisation des chaleurs en lot',
 'reproduction', 'expert',
 'L''altrenogest (Regumate) administré 18 jours déclenche des chaleurs synchronisées 5-7j après arrêt, permettant la conduite en bande.',
 E'## Principe\n\nDonner un progestagène (altrenogest oral) pendant **18 jours consécutifs** bloque l''œstrus. À l''arrêt, **toutes les truies viennent en chaleur dans une fenêtre de 4-7 jours**.\n\n## Protocole standard\n\n- **J1-J18** : 20 mg altrenogest/truie/jour dans l''aliment\n- **J19-J25** : arrêt → chaleurs groupées\n- **J22-J25** : IA des truies en chaleur\n\n## Intérêts\n\n- **Conduite en bande** : groupes homogènes de mises-bas\n- **Optimisation main-d''œuvre** : tâches groupées\n- **Vide sanitaire** plus efficace entre bandes\n- **Charge maternité** prédictible\n\n## Limites\n\n- **Coût** : ~3-5 000 FCFA/truie/cycle\n- Réservé aux **cochettes et truies cyclées normales** (pas d''anœstrus)\n- Ordonnance vétérinaire obligatoire\n- Manipulation hygiénique (hormone, gants)\n\n## Alternative économique\n\n- **Effet mâle groupé** : exposer plusieurs truies au verrat simultanément 2x/jour pendant 3-4 jours déclenche partiellement la synchronisation (60-70% du lot en chaleur sur 5j).',
 ARRAY['synchronisation', 'altrenogest', 'bande', 'regumate'],
 'IFIP, ITP'),

('refonte-cochettes', 'Cochettes : préparation au premier service',
 'reproduction', 'intermediaire',
 'Les cochettes doivent être saillies à 220-240 jours, 130-140 kg, après 2-3 cycles observés. Préparer avec un flushing 14j avant.',
 E'## Critères pour la 1ère saillie\n\n| Critère | Valeur cible |\n|---|---|\n| Âge | 220-240 jours (~7-8 mois) |\n| Poids | 130-140 kg |\n| Épaisseur lard dorsal | 14-18 mm |\n| Cycles observés | 2-3 minimum |\n\n## Pourquoi attendre le 2e/3e cycle ?\n\n- Le **1er cycle** a peu d''ovulations (8-10) → petite portée\n- **2e cycle** : 12-14 ovulations\n- **3e cycle** : pleine maturité (14-18 ovulations)\n\n## Préparation 14 jours avant\n\n- **Flushing** : concentré + 0.5 kg supplément/jour\n- Hausse de la prise alimentaire = augmente le taux d''ovulation de 1-2 ovules\n- Effet **verrat** quotidien dès J-21\n\n## Erreurs courantes\n\n1. Saillir trop jeune → petite portée, longévité réduite\n2. Saillir trop grosse (> 150 kg) → problèmes locomoteurs\n3. Pas de flushing → ovulation faible\n4. Pas d''effet verrat → cochette non préparée hormonalement',
 ARRAY['cochette', 'premier-service', 'flushing', 'puberte'],
 'INRA, IFIP'),

('reforme-truies-criteres', 'Réformer une truie : 5 critères',
 'reproduction', 'intermediaire',
 'Réformer après 6-7 portées ou si : 2 retours en chaleur consécutifs, portée < 8 vivants 2 fois, mammites/métrites répétées, boiterie chronique.',
 E'## Critères de réforme\n\n### 1. Âge productif\n- **6-7 portées** = fin de vie productive normale\n- Au-delà, productivité chute (< 10 porcelets/portée)\n\n### 2. Performance reproductive\n- **2 retours en chaleur consécutifs** (= 2 échecs de gestation)\n- **2 portées consécutives < 8 porcelets vivants**\n- **ISS > 15 jours** récurrent\n\n### 3. Santé\n- **Mammites/métrites répétées** (3+ épisodes)\n- **Prolapsus utérin** ou vaginal\n- **Boiterie chronique** (locomotion altérée 4+ semaines)\n\n### 4. Comportement\n- Agressive envers porcelets (écrasement répété)\n- Refus de téter (allaitement insuffisant)\n\n### 5. Économique\n- Productivité < seuil ferme (ex: < 22 porcelets/an)\n\n## Calcul économique\n\n**Marge truie/an** = (porcelets sevrés × prix) - (aliment + amortissement)\n\nSi marge < 0 sur 2 portées consécutives → réformer\n\n## Renouvellement\n\nTaux annuel cible : **30-40% de renouvellement**',
 ARRAY['reforme', 'productivite', 'longevite', 'truie'],
 'IFIP, INRA'),

-- ========================================================
-- SANITAIRE (10 tips)
-- ========================================================

('sas-sanitaire-entree', 'Aménager un sas sanitaire d''entrée',
 'sanitaire', 'debutant',
 'Le sas sanitaire est la 1ère ligne de défense biosécurité : pédiluve, vestiaire séparant zone propre et zone sale, lavage des mains.',
 E'## Conception en 3 zones\n\n```\nEXTÉRIEUR → [pédiluve] → ZONE SALE → [bench/banc] → ZONE PROPRE → ÉLEVAGE\n```\n\n## Équipement minimum\n\n1. **Pédiluve à l''entrée** : bac 5L, désinfectant renouvelé chaque jour (cresyl, formol dilué, ou eau de javel 1%)\n2. **Vestiaire zone sale** : déposer ses vêtements de ville, bottes\n3. **Lavabo + savon** : lavage des mains obligatoire\n4. **Vestiaire zone propre** : tenue de ferme propre (combinaison + bottes dédiées)\n5. **Registre visiteurs** : date, nom, dernière visite porcine\n\n## Règle "douche" pour visiteurs externes\n\n- Si visiteur venant d''un autre élevage porcin **< 48h** : refuser ou exiger douche complète + tenue ferme\n- **48h-7j** : douche + tenue ferme\n- **> 7j** : tenue ferme suffit\n\n## Coût\n\nSas basique : **150-300 000 FCFA** (matériaux locaux + plomberie simple)',
 ARRAY['biosecurite', 'sas', 'peluve', 'visiteurs'],
 'OIE, FAO biosécurité porcine'),

('peste-porcine-africaine-prevention', 'Peste Porcine Africaine : 7 règles de prévention',
 'sanitaire', 'expert',
 'La PPA est mortelle à 95%, sans vaccin, présente en Afrique de l''Ouest. La prévention passe uniquement par la biosécurité stricte.',
 E'## Pourquoi c''est critique\n\n- **Mortalité 95-100%** chez le porc\n- **Pas de vaccin** disponible en Afrique\n- **Présente en CI** (foyers signalés 2019-2024)\n- Virus très résistant : survit **18 mois** dans les viandes congelées\n\n## Les 7 règles strictes\n\n### 1. Pas de déchets de cuisine\n- **Interdit** de donner reliefs de table aux porcs (risque viande contaminée importée)\n\n### 2. Sas et pédiluve fonctionnels\n- Renouveler quotidiennement\n\n### 3. Quarantaine 30 jours\n- Tous nouveaux animaux isolés et observés\n\n### 4. Pas de contact avec porcs externes\n- Pas de foires, marchés, élevages voisins sans précaution\n\n### 5. Lutte contre tiques molles (Ornithodoros)\n- Vecteurs naturels du virus\n\n### 6. Lutte rongeurs/oiseaux\n- Vecteurs mécaniques\n\n### 7. Surveillance et déclaration\n- Mortalité brutale + fièvre + hémorragies → **ALERTE VÉTÉRINAIRE IMMÉDIATE**\n- Déclaration obligatoire MIRAH\n\n## Signes cliniques PPA\n\n- Fièvre 41°C+\n- Mortalité brutale (24-72h)\n- Cyanose oreilles/abdomen\n- Hémorragies cutanées et internes\n- Avortements truies\n\n## En cas de suspicion\n\n- **Isoler le bâtiment**\n- **Appeler vétérinaire/MIRAH** d''urgence\n- **Pas de mouvement d''animaux ni de personnel** hors ferme',
 ARRAY['ppa', 'peste-porcine', 'biosecurite', 'alerte'],
 'OIE/WOAH, FAO EMPRES, MIRAH CI'),

('calendrier-vaccinal-porcelet', 'Calendrier vaccinal porcelet J1-J100',
 'sanitaire', 'intermediaire',
 'Calendrier de référence : Fer J1, Coccidiostatique J3, castration J7, Mycoplasma J14, Vermifuge J21, Vaccin sevrage J42.',
 E'## Calendrier standard CI\n\n| Âge | Acte | Produit | Voie | Dose |\n|---|---|---|---|---|\n| **J1** | Fer dextran | Fer 100 mg/ml | IM | 2 ml |\n| **J3** | Coccidiostatique | Toltrazuril 5% (Baycox) | Orale | 1 ml |\n| **J7** | Castration mâles | Antiseptique + méloxicam | Topique | — |\n| **J14** | Vaccin Mycoplasma primo | Mhyo inactivé | IM | 2 ml |\n| **J21** | Vermifuge | Ivermectine 1% | SC | 0.3 ml/10kg |\n| **J28** | Mycoplasma rappel + Circovirus | Mhyo + PCV2 | IM | 2 ml |\n| **J42** | Peste classique + Rouget | PPC + Erysipelothrix | IM | 2 ml |\n| **J56** | Vermifuge rappel | Ivermectine 1% | SC | 0.3 ml/10kg |\n| **J70** | Parvo + Lepto (futurs reproducteurs) | Parvo + Lepto | IM | 2 ml |\n| **J100** | Pasteurellose | Pasteurella multocida | IM | 2 ml |\n\n## Règles d''or\n\n- **Aiguille neuve par animal** (ou désinfection)\n- **Site IM** : encolure (porcelet) ou cuisse (adulte)\n- **Conservation 2-8°C** (jamais congelé)\n- **Reconstitution** : utiliser dans les 2h\n- **Registre** : noter chaque acte (carnet d''élevage)\n\n## Coût annuel par porcelet\n\n~ **800-1 500 FCFA** de vaccins/porcelet jusqu''au sevrage',
 ARRAY['vaccination', 'calendrier', 'porcelet', 'protocole'],
 'OIE, IFIP, MIRAH'),

('diarrhee-porcelets-diagnostic', 'Diarrhée porcelets : diagnostic différentiel',
 'sanitaire', 'expert',
 'Diarrhée néonatale (< 7j) = E. coli K88, rotavirus. Post-sevrage = E. coli, salmonelles, coccidies. Différencier avant traitement.',
 E'## Diagnostic par âge\n\n### Néonatale (J1-J7)\n| Cause | Couleur diarrhée | Particularité |\n|---|---|---|\n| **E. coli K88** | Jaune-blanche, aqueuse | Toute la portée touchée, mortalité 50%+ |\n| **Rotavirus** | Jaune, mousseuse | Vomissements associés |\n| **Coccidiose (Isospora)** | Jaune pâle, pâteuse | J7-J21, déshydratation |\n| **C. perfringens type C** | Rouge sanglante | Mortalité brutale J1-J3 |\n\n### Post-sevrage (J21-J50)\n| Cause | Particularité |\n|---|---|\n| **E. coli post-sevrage** | Boiteries œdémateuses parfois associées |\n| **Salmonellose** | Fièvre, parfois septicémie |\n| **Coccidiose** | Persistance malgré antibio |\n| **TGE** | Très contagieuse, toute la bande |\n\n## Démarche diagnostique\n\n1. **Coproculture** vétérinaire (identifier germe)\n2. **Compter porcelets atteints / portée**\n3. **Mesurer la déshydratation** (pli cutané, yeux enfoncés)\n4. **Réhydrater immédiatement** (eau + sel + glucose, ou solution réhydratante)\n\n## Traitements\n\n- **E. coli** : amoxicilline 15 mg/kg ou colistine orale\n- **Coccidiose** : toltrazuril 20 mg/kg orale, 1 prise\n- **Salmonelles** : enrofloxacine 5 mg/kg, IM ou orale, 3-5j\n- **Virale (rota, TGE)** : seulement soutien (hydratation, environnement chaud)\n\n## Prévention\n\n- Colostrum dans les 6h\n- Hygiène maternité stricte\n- Vaccination truies en fin de gestation (E. coli, rotavirus)\n- Aliment de pré-sevrage progressif',
 ARRAY['diarrhee', 'porcelets', 'ecoli', 'coccidiose', 'antibio'],
 'INRA, CIRAD, IFIP, OIE'),

('quarantaine-nouveaux-animaux', 'Quarantaine des nouveaux animaux : 30 jours',
 'sanitaire', 'intermediaire',
 'Tout nouvel animal entrant doit être isolé 30 jours minimum dans un bâtiment séparé, avec observation, dépistage et acclimatation.',
 E'## Pourquoi 30 jours minimum\n\nPériode d''incubation de la plupart des maladies porcines :\n- PPA : 4-19 jours\n- PPC : 5-14 jours  \n- Mycoplasmose : 14-21 jours\n- Gale : 14-21 jours\n\n**30 jours couvre largement** ces incubations.\n\n## Conditions de quarantaine\n\n1. **Bâtiment isolé**, à 50m+ des autres porcheries\n2. **Personnel dédié** ou intervention en fin de tournée\n3. **Matériel séparé** (auge, brosse, bottes)\n4. **Ne JAMAIS introduire dans l''élevage avant 30j d''observation**\n\n## Surveillance quotidienne\n\n- Température (rectale 2x/sem)\n- Appétit\n- Lésions cutanées (gale)\n- Comportement, démarche\n- Toux\n\n## Examens à J0 et J21\n\n- Prélèvement sérologique : PPA, PPC, parvo, lepto (vétérinaire)\n- Coproscopie : parasitisme\n\n## Vaccinations d''adaptation\n\n- Faire suivre le protocole de la ferme (mycoplasme, parvo-lepto)\n- Mise en contact progressive (échantillon de fèces de la ferme pour immunité d''écosystème)\n\n## Coût d''une mauvaise quarantaine\n\nUn seul animal porteur de PPA = perte de l''élevage entier (95% mortalité).',
 ARRAY['quarantaine', 'biosecurite', 'nouveaux-animaux'],
 'OIE, FAO, IFIP'),

('antibiotiques-usage-raisonne', 'Antibiotiques : usage raisonné',
 'sanitaire', 'expert',
 'Antibiothérapie = uniquement sur ordonnance, après diagnostic, avec respect du délai d''attente avant abattage. Risque antibiorésistance.',
 E'## Règles d''or\n\n1. **Diagnostic d''abord** : pas d''antibio "à l''aveugle"\n2. **Ordonnance vétérinaire obligatoire** (CI : Code de la Santé Animale)\n3. **Dose et durée respectées** (sous-dose = résistance)\n4. **Délai d''attente** strict avant abattage\n5. **Pas de prophylaxie systématique**\n\n## Antibiotiques courants porc\n\n| Molécule | Indication | Voie | Délai abattage |\n|---|---|---|---|\n| **Amoxicilline LA** | Respiratoire, polyvalent | IM | 21 j |\n| **Tylosine** | Pulmonaire, digestif | IM/orale | 8 j |\n| **Enrofloxacine** | Sévères, salmonelles | IM | 10 j |\n| **Oxytétracycline LA** | Polyvalent | IM | 28 j |\n| **Colistine** | Diarrhée E. coli | Orale | 1 j |\n| **Sulfa-triméthoprime** | Coccidiose, respi | Orale | 15 j |\n| **Florfénicol** | Respiratoire | IM | 14 j |\n\n## Antibiorésistance : signes\n\n- Traitement habituel ne marche plus\n- Mortalité malgré antibio\n- Récidive rapide post-traitement\n\n→ **Antibiogramme** chez le vétérinaire\n\n## Bonnes pratiques anti-résistance\n\n- **Rotation** des familles d''antibio\n- **Pas de combinaisons** non validées\n- **Carnet d''élevage** : tracer chaque traitement\n- **Vacciner > traiter** (prévention coûte moins cher)\n- **Réformer** les chroniques (réservoirs)\n\n## Risque réglementaire\n\nRésidus antibio en abattoir = saisie carcasse + amende. Toujours respecter le **délai d''attente**.',
 ARRAY['antibiotiques', 'antibioresistance', 'delai-attente', 'prescription'],
 'OMS, OIE, ANSES'),

('mycoplasmose-pulmonaire', 'Mycoplasmose pulmonaire : reconnaître et gérer',
 'sanitaire', 'intermediaire',
 'Toux sèche, persistante, dans les bandes d''engraissement. Maladie endémique en CI. Vaccination J14+J28 et traitement tylosine si crise.',
 E'## Maladie\n\n**Mycoplasma hyopneumoniae** = pneumonie enzootique du porc. Très répandue en CI.\n\n## Signes cliniques\n\n- **Toux sèche chronique**, surtout après stress (mise en mouvement, changements de bâtiment)\n- Touche bande entière, pas mortalité aiguë\n- **Croissance ralentie** (-10 à -15% GMQ)\n- Lésions pulmonaires visibles à l''abattoir (zone craniale)\n\n## Diagnostic\n\n- Clinique (toux groupée bande engraissement)\n- Confirmation : sérologie ELISA ou PCR (vétérinaire)\n- Inspection carcasses à l''abattoir\n\n## Traitement\n\n- **Tylosine** 10 mg/kg/j orale ou IM, 5 jours\n- Ou **enrofloxacine** 5 mg/kg/j IM, 3-5 jours\n- Améliorer ventilation, baisser poussières\n\n## Prévention (clé)\n\n- **Vaccination J14 primo + J28 rappel** (système Smart Farm)\n- **Truies vaccinées** transmettent immunité\n- **All-in/all-out** strict\n- **Vide sanitaire** entre bandes\n- Bonne ventilation (pas de courants d''air mais renouvellement air)\n\n## Coût\n\n- Vaccination : ~300-500 FCFA/porcelet × 2 doses\n- Sans vaccin : perte croissance ~ 2-3 kg/porc à 100 kg = 4-6 000 FCFA/porc\n- **ROI vaccination = 5-10x**',
 ARRAY['mycoplasmose', 'pneumonie', 'toux', 'vaccin'],
 'IFIP, CIRAD, INRA'),

('detection-precoce-5-points', 'Check quotidien 5 points pour détection précoce',
 'sanitaire', 'debutant',
 'Faire une tournée matinale et vérifier 5 points : appétit, démarche, fèces, respiration, comportement. Détecter dans les 24h gagne 80% du traitement.',
 E'## Les 5 points de la tournée matin\n\n### 1. Appétit\n- Aliment restant dans l''auge = anormal\n- Animal qui ne mange pas → fièvre probable\n\n### 2. Démarche\n- Boiterie, prostration, raideur\n- Truie qui peine à se lever\n\n### 3. Fèces et urines\n- Diarrhée (couleur, consistance)\n- Sang dans urines/fèces\n- Constipation (peu/sec)\n\n### 4. Respiration\n- Toux audible\n- Respiration accélérée (> 40/min adulte)\n- Halètement par la bouche = urgence\n\n### 5. Comportement\n- Isolé du groupe\n- Apathie, oreilles tombantes\n- Agressivité inhabituelle\n- Hyper-vocalisations\n\n## Outils\n\n- Thermomètre rectal (T° normale porc : 38.5-39.5°C)\n- Carnet d''observation par case/bâtiment\n- Lampe torche si tournée tôt\n\n## Tempo\n\n- **Matin** : à jeun, les animaux montrent l''appétit\n- **Soir** : avant nourrissage, animaux calmes = signes maladie visibles\n\n## Règle d''or\n\n**Détecter à J1 = 80% de chances de guérison**\n**Détecter à J3 = 50%**\n**Détecter à J5 = 20%**',
 ARRAY['surveillance', 'detection', 'tournee', 'temperature'],
 'IFIP, INRA'),

('vermifugation-protocole', 'Vermifugation porcine : protocole annuel',
 'sanitaire', 'intermediaire',
 'Ivermectine SC ou orale, 2x/an pour reproducteurs, 1x au sevrage et 1x à mi-engraissement pour porcelets.',
 E'## Parasites principaux\n\n- **Ascaris suum** (vers ronds intestinaux) : retard croissance, foie tigré abattoir\n- **Strongyloides** (parasitose néonatale)\n- **Trichures, Oesophagostomes**\n- **Gale sarcoptique** (parasite cutané)\n\n## Protocole standard\n\n### Reproducteurs (truies, verrats)\n- **Ivermectine 1% SC 0.3 ml/10 kg, 2x/an**\n- Ou en gestation (vers 90 j) et post-sevrage\n\n### Porcelets\n- **J21** : ivermectine SC (porcelet)\n- **J56** (post-sevrage) : rappel\n- **J100** si engraissement long\n\n## Molécules\n\n| Molécule | Voie | Spectre | Délai abattage |\n|---|---|---|---|\n| **Ivermectine 1%** | SC | Larges + gale | 28 j |\n| **Fenbendazole** | Orale | Vers ronds | 14 j |\n| **Lévamisole** | SC ou orale | Vers ronds | 7 j |\n| **Doramectine** | IM | Larges + gale | 35 j |\n\n## Rotation des familles\n\nPour éviter résistances : changer de famille tous les 2-3 ans\n- Année 1-2 : ivermectine\n- Année 3 : fenbendazole\n- Année 4 : retour ivermectine\n\n## Coproscopie de contrôle\n\n- 1x/an minimum (vétérinaire)\n- Quantifie l''excrétion d''œufs\n- Décide si protocole suffisant',
 ARRAY['vermifuge', 'parasites', 'ivermectine', 'ascaris'],
 'OIE, IFIP'),

-- ========================================================
-- NUTRITION (10 tips)
-- ========================================================

('comprendre-mat-em-lysine', 'Comprendre MAT, EM et Lysine',
 'nutrition', 'debutant',
 'MAT (protéine) = construction des tissus. EM = énergie pour vivre/grandir. Lysine = acide aminé limitant n°1 chez le porc.',
 E'## Les 3 piliers nutritionnels\n\n### MAT (Matière Azotée Totale)\n- = protéines brutes (%)\n- Construit les tissus (muscles, organes)\n- Sources : tourteau soja (47%), arachide (45%), poisson (60%)\n- **Trop = gaspillage** (excrété en urée, pollue)\n- **Pas assez** = retard croissance\n\n### EM (Énergie Métabolisable)\n- = énergie utilisable (kcal/kg)\n- Carburant pour vivre + grandir\n- Sources : maïs (3300), sorgho (3250), huile palme (8500)\n- **Trop** = animal trop gras\n- **Pas assez** = arrêt croissance\n\n### Lysine\n- = 1er acide aminé limitant\n- Si pas assez de lysine → la MAT entière est gaspillée\n- "Loi du minimum"\n- Cible : ~1% en croissance, 1.3% en porcelet\n\n## Cibles par stade (NRC 2012)\n\n| Stade | MAT % | EM kcal | Lys % |\n|---|---|---|---|\n| Porcelet 1er âge | 21 | 3400 | 1.35 |\n| Porcelet 2e âge | 19 | 3350 | 1.20 |\n| Croissance | 17 | 3250 | 1.00 |\n| Finition | 14.5 | 3200 | 0.80 |\n| Gestante | 13 | 3100 | 0.55 |\n| Allaitante | 18 | 3300 | 1.00 |\n| Verrat | 14 | 3150 | 0.60 |',
 ARRAY['mat', 'em', 'lysine', 'fondamentaux'],
 'NRC 2012, INRA 2018'),

('formule-croissance-mais-soja-son', 'Formule croissance maïs-soja-son',
 'nutrition', 'intermediaire',
 'Formule type pour porcs 30-60 kg : 60% maïs + 22% tourteau soja + 15% son blé + 3% prémix/calcaire = MAT 17%, EM 3036 kcal.',
 E'## Recette\n\n| Ingrédient | % | MAT apport | EM apport |\n|---|---|---|---|\n| Maïs grain | 60 | 4.8 | 1980 |\n| Tourteau soja 48% | 22 | 10.34 | 726 |\n| Son de blé | 15 | 2.4 | 330 |\n| Prémix + CaCO₃ | 3 | 0 | 0 |\n| **Total** | **100** | **17.5%** | **3036** |\n\n## Évaluation\n\n- ✅ MAT : 17.5% ≥ cible 17% NRC 2012\n- ⚠️ EM : 3036 < cible 3250 (-6.6%)\n- ⚠️ Lysine : ~0.91% < cible 1.00% (-9%)\n- ⚠️ Ca/P : déficient en calcium\n\n## Améliorations\n\n- Ajouter **2% huile de palme** → EM +170 kcal\n- Ajouter **L-Lysine HCl** 0.1% → comble lysine\n- **CaCO₃** 1.5% → corrige Ca\n\n## Coût indicatif (prix CI 2025)\n\n- Maïs 280 FCFA × 0.60 = 168\n- Tourteau soja 480 × 0.22 = 106\n- Son blé 180 × 0.15 = 27\n- Prémix 1500 × 0.03 = 45\n- **Total ≈ 345 FCFA/kg**\n\n## Distribution porc 30-60 kg\n\n- 1.8 à 2.5 kg/jour selon poids\n- 2 repas (matin + soir)\n- Eau ad libitum',
 ARRAY['formule', 'croissance', 'mais', 'soja'],
 'NRC 2012, INRA 2018, IFIP'),

('aflatoxines-prevention', 'Aflatoxines : prévention vigilance maïs/arachide',
 'nutrition', 'expert',
 'Aflatoxines (Aspergillus flavus) dans maïs/arachide stockés humides. Toxicité hépatique, immunosuppression. Limite 20 ppb.',
 E'## Qu''est-ce ?\n\nL''**aflatoxine B1** est une mycotoxine produite par *Aspergillus flavus* sur céréales et arachides stockées en milieu humide chaud.\n\n## Contexte CI\n\nClimat tropical humide = **risque élevé** pendant saison des pluies. Maïs et arachide locaux particulièrement à risque.\n\n## Effets sur le porc\n\n- **Hépatotoxique** : foie tuméfié, jaunisse\n- **Immunosuppression** : maladies opportunistes\n- **Retard croissance** dose-dépendant\n- **Lait contaminé** truie → porcelets affectés\n- **Reproduction** : avortements, mort-nés\n- **Carcinogène** (long terme)\n\n## Seuils légaux porc (UE/OIE)\n\n- Aliment porcs : **20 ppb max** (porcs en finition)\n- Aliment porcelets/truies : **5-10 ppb max**\n- Lait : 0.05 ppb (humain)\n\n## Prévention au stockage\n\n1. **Séchage maïs à < 14% humidité** avant stockage\n2. **Aération** des silos/sacs\n3. **Bâche bien tendue** (pas de condensation)\n4. **Rotation FIFO** (premier entré, premier sorti)\n5. **Inspection visuelle** : moisissures vertes/jaunes = jeter\n\n## Test rapide\n\n- **Bandelettes ELISA aflatoxine** (5-10 000 FCFA/test)\n- Laboratoires CI : LANADA, université\n\n## Traitement aliment contaminé\n\n- **Liants à mycotoxines** : bentonite (charbon activé alimentaire) ajoutée à 0.5-1% de l''aliment\n- Réduit absorption mais ne neutralise pas totalement\n- Si > 50 ppb : **ne pas donner**, détruire',
 ARRAY['aflatoxines', 'mycotoxines', 'stockage', 'mais'],
 'FAO, ANSES, CIRAD'),

('eau-besoin-quotidien', 'Eau : besoin quotidien par catégorie',
 'nutrition', 'debutant',
 'Eau = nutriment n°1. Porcelet 1-2 L/j, croissance 5-7 L/j, truie allaitante 25-35 L/j. Manque d''eau = manque d''aliment.',
 E'## Besoins quotidiens (litres/jour)\n\n| Catégorie | Hiver | **Climat CI (chaud)** |\n|---|---|---|\n| Porcelet sevré (10-20 kg) | 2 | **3-4** |\n| Croissance (20-50 kg) | 5 | **6-8** |\n| Finition (50-110 kg) | 8 | **10-15** |\n| Truie gestante | 12 | **15-20** |\n| Truie allaitante | 25 | **25-40** |\n| Verrat | 12 | **15-20** |\n\n## Pourquoi l''eau est critique\n\n- Représente **70-80%** du corps\n- Régule la température (climat tropical CI)\n- **Pas d''eau = pas de prise alimentaire** (1 L manquant = 200-400 g d''aliment refusé)\n- Lactation truie : 1 L de lait = 3 L d''eau\n\n## Équipement\n\n### Abreuvoirs goutte-à-goutte (tétine)\n- Débit : 0.5-1 L/min (truie allaitante)\n- Hauteur : à la hauteur du dos de l''animal\n- 1 tétine pour 10-12 animaux\n\n### Abreuvoirs auge\n- Plus fragiles (souillures)\n- 1 cm de bord par animal\n\n## Contrôles\n\n- **Débit hebdomadaire** : tester chaque tétine\n- **Qualité bactériologique** : analyse 1x/an (LANADA)\n- **pH** : 6.5-8.5 idéal\n- **Température** : < 25°C',
 ARRAY['eau', 'abreuvement', 'tetine', 'besoin'],
 'NRC 2012, INRA 2018'),

('manioc-aliment-energetique', 'Manioc séché : substitut énergétique du maïs',
 'nutrition', 'intermediaire',
 'Le manioc séché remplace jusqu''à 30% du maïs dans une formule. MAT 2.5%, EM 3200, lysine 0.10% — compense avec tourteau.',
 E'## Atouts\n\n- **Disponibilité locale CI** : production importante\n- **Prix** plus bas que maïs en saison de pic\n- **EM 3200 kcal/kg** = comparable au maïs\n- Stocke bien sec\n\n## Limites\n\n- **MAT seulement 2.5%** (vs maïs 8%) → besoin plus de tourteau\n- **Pauvre en acides aminés** (lysine 0.10%, méthionine 0.04%)\n- **Toxicité cyanogénique** si mal séché (acide cyanhydrique)\n- Goût parfois rebutant si frais\n\n## Préparation\n\n1. **Pelage** des racines\n2. **Trempage 24-48h** (élimine cyanures)\n3. **Séchage soleil 3-7 jours** ou séchoir 60°C\n4. **Broyage** en farine ou cossettes\n5. **Stockage sec** (humidité < 13%)\n\n## Formule type avec manioc\n\n| Ingrédient | % |\n|---|---|\n| Maïs grain | 30 |\n| **Manioc séché** | **20** |\n| Tourteau soja 48% | 30 |\n| Son blé | 17 |\n| Prémix + CaCO₃ + Sel | 3 |\n\n**Compensation** : on monte le tourteau soja à 30% (au lieu de 22%) pour compenser MAT et lysine.\n\n## Coût CI 2025\n\n- Manioc séché : **150-200 FCFA/kg**\n- Maïs : 250-300 FCFA/kg\n- Économie : 30% × 100 FCFA = **30 FCFA/kg** d''aliment formulé',
 ARRAY['manioc', 'alternative', 'mais', 'cossettes'],
 'CIRAD, FAO, IRAT'),

('truie-allaitante-rationnement', 'Truie allaitante : ration ad libitum',
 'nutrition', 'expert',
 'Truie allaitante : MAT 18%, EM 3300+. Distribution croissante J1 (3 kg) à J10 (6-7 kg). Eau 35 L/j minimum.',
 E'## Pourquoi c''est crucial\n\n- La truie produit **8-12 L de lait/jour** (8 000 kcal/j)\n- Si pas assez nourrie → **mobilisation des réserves corporelles** → ISS allongé\n- Lactation longue + déficit = anœstrus post-sevrage\n\n## Plan de rationnement (truie 200 kg, portée 10 porcelets)\n\n| Jour | Aliment kg/jour | Eau L/j |\n|---|---|---|\n| J0 (mise-bas) | 1.5-2 (léger pour éviter MMA) | 25 |\n| J1-J3 | 2.5-3.5 | 30 |\n| J4-J7 | 4-5 | 35 |\n| J8-J14 | 5-6 | 35 |\n| J15-sevrage | **6-7 (ad libitum)** | 40 |\n\n## Formule allaitante (MAT 18%, EM 3300)\n\n| Ingrédient | % |\n|---|---|\n| Maïs grain | 50 |\n| Tourteau soja 48% | 25 |\n| Son blé | 12 |\n| Farine de poisson | 5 |\n| Huile de palme | 2 |\n| **Prémix + CaCO₃ + sel** | **6** |\n\n## Astuces tropicales CI\n\n- **Repas frais** : matin (5-6h) et soir (17-18h)\n- **Évite le pic chaleur 12-15h** (truie refuse de manger)\n- **Brumisation** maternité pour stimuler l''appétit\n- **3 repas/j** plutôt que 2 = +500 g consommés/j\n\n## Économie\n\n- Truie sous-nourrie en lactation = **-2 porcelets/portée** suivante\n- Gain pleine alimentation : 0.4 porcelet en plus × 2 portées/an = ~**16 000 FCFA**',
 ARRAY['truie-allaitante', 'rationnement', 'lactation'],
 'NRC 2012, INRA 2018, IFIP'),

('aliment-porcelet-sevrage', 'Aliment porcelet sevré : transition douce',
 'nutrition', 'intermediaire',
 'Pre-starter J21-J35 (MAT 22%, lait sec, prébiotiques), puis Starter J35-J60. Pas de transition brutale = pas de diarrhée.',
 E'## Phases d''alimentation porcelet\n\n### Pre-starter (J7 creep feeding → J35)\n- **Très digestible** : protéines de lait sec, plasma\n- **MAT 22-23%**, EM 3450 kcal\n- Texture : granulés petits ou farine fine\n- **Prébiotiques + acidifiants** pour stabiliser flore\n- Coût : 800-1 200 FCFA/kg (cher mais consommation faible)\n\n### Starter (J35-J60)\n- **MAT 20-21%**, EM 3400\n- Transition vers protéines végétales (tourteau soja extrudé)\n- **Coccidiostatique** parfois inclus\n- Coût : 600-800 FCFA/kg\n\n### Croissance (J60-J100)\n- MAT 17-18%, EM 3250\n- Formule classique maïs-soja-son\n\n## Transitions critiques\n\n### Au sevrage (J21-J28)\n- **Mélanger 70% pre-starter + 30% nouveau** pendant 3 j\n- Puis 30/70 pendant 3 j\n- Puis 100% nouveau\n- **Eau acidifiée** (pH 4.5) limite E. coli\n\n### Pre-starter → Starter\n- Mélange progressif sur 5 j\n\n## Erreurs courantes\n\n1. Passer brutalement → diarrhée post-sevrage massive\n2. Pre-starter trop tôt arrêté → retard croissance\n3. Eau froide ou sale → refus aliment\n4. Pas d''aliment de pré-sevrage en maternité → choc sevrage\n\n## Coût et ROI\n\n- Pre-starter : 1 kg consommé/porcelet = **800-1 200 FCFA**\n- Mais **gain GMQ post-sevrage +50 g/j × 30 j** = **+1.5 kg poids** à J60 = ~2 500 FCFA gagnés à la vente.\n- **ROI 2-3x** sur le pre-starter',
 ARRAY['porcelet', 'sevrage', 'pre-starter', 'transition'],
 'NRC 2012, IFIP, INRA'),

('indice-consommation-cible', 'Indice de consommation (IC) : cibles et calcul',
 'nutrition', 'intermediaire',
 'IC = kg aliment / kg vif produit. Cibles : porcelet 1.3-1.5, croissance 2.3-2.7, finition 2.8-3.2.',
 E'## Définition\n\n**IC = kg d''aliment consommé / kg de poids vif gagné**\n\nIndicateur n°1 d''efficacité économique d''un élevage.\n\n## Cibles par stade\n\n| Stade | IC objectif | IC moyen CI |\n|---|---|---|\n| Porcelet sevré (8-25 kg) | 1.3-1.5 | 1.6-1.8 |\n| Croissance (25-60 kg) | 2.3-2.7 | 2.7-3.0 |\n| Finition (60-110 kg) | 2.8-3.2 | 3.2-3.8 |\n| **Engraissement global (8-110 kg)** | **2.6-3.0** | **3.0-3.4** |\n\n## Calcul pratique\n\n**Exemple bande de 50 porcs**\n- Poids départ : 50 × 8 kg = 400 kg\n- Poids sortie : 50 × 100 kg = 5 000 kg\n- **Gain total** : 4 600 kg\n- Aliment consommé sur la période : 14 200 kg\n- **IC = 14 200 / 4 600 = 3.09**\n\n## Économie\n\n**Réduire IC de 3.4 à 3.0 sur un porc de 100 kg :**\n- Gain : (3.4 - 3.0) × (100 - 8) = 36.8 kg d''aliment économisé\n- Au prix 350 FCFA/kg = **12 880 FCFA/porc**\n- Sur 50 porcs/an = **644 000 FCFA**\n\n## Facteurs d''amélioration IC\n\n1. **Qualité aliment** (digestibilité, MAT optimale)\n2. **Génétique** (lignées performantes)\n3. **Eau** disponible 24h/24\n4. **Densité** non excessive (stress = +0.2 IC)\n5. **Santé** (animaux malades = IC dégradé)\n6. **Température** (au-delà de 28°C, IC monte)\n7. **Réduction gaspillage** (auge non débordante)\n\n## Suivi\n\nCalculer IC **par bande** à la sortie. Tableau de bord mensuel.',
 ARRAY['ic', 'efficacite', 'indicateur', 'cout'],
 'NRC, INRA, IFIP, BIPORC'),

('cout-formule-fcfa', 'Calculer le coût d''une formule en FCFA/kg',
 'nutrition', 'debutant',
 'Coût formule = Σ (% ingrédient × prix kg). Cible : croissance 300-380 FCFA/kg, finition 280-350, porcelet 600-900.',
 E'## Méthode\n\n**Coût formule (FCFA/kg) = Σ (% ingrédient × prix kg)**\n\n## Exemple croissance maïs-soja-son\n\n| Ingrédient | % | Prix FCFA/kg | Apport coût |\n|---|---|---|---|\n| Maïs grain | 60 | 280 | 168 |\n| Tourteau soja 48% | 22 | 480 | 105.6 |\n| Son blé | 15 | 180 | 27 |\n| Prémix + CaCO₃ + sel | 3 | 1500 | 45 |\n| **Total** | **100** | | **345.6 FCFA/kg** |\n\n## Cibles CI 2025\n\n| Type aliment | FCFA/kg |\n|---|---|\n| Porcelet pre-starter | 800-1 200 |\n| Porcelet starter | 550-700 |\n| Croissance | 300-380 |\n| Finition | 280-350 |\n| Truie gestante | 250-320 |\n| Truie allaitante | 320-400 |\n\n## Optimisation\n\n### Substituer maïs ↗ par manioc ↘\n- Économie : 30 FCFA/kg × 30% = 9 FCFA/kg formule\n- Mais : ajuster tourteau soja en compensation\n\n### Saisonnalité matières premières\n- **Maïs** : plus cher en saison sèche (juin-août)\n- **Acheter en récolte** (oct-déc) pour stocker\n- Économie : **30-40 FCFA/kg** sur achats stratégiques\n\n### Concentré industriel vs fait-maison\n| | Faits-maison | Concentré industriel |\n|---|---|---|\n| Coût/kg | 280-380 | 500-800 |\n| Temps | + | - |\n| Qualité | Variable | Constante |\n| Quantité min | Sacs 50 kg | Sacs 50 kg |\n\nÉconomie fait-maison : **40-50%** mais exige formulation rigoureuse et matières premières disponibles.',
 ARRAY['cout', 'fcfa', 'formule', 'economie'],
 'IFIP, BIPORC, prix marché CI 2025'),

('stockage-matieres-premieres', 'Stockage matières premières : règles d''or',
 'nutrition', 'debutant',
 'Humidité < 13%, ventilation, palettes au sol, FIFO, lutte rongeurs. Pertes mauvais stockage = 10-20% des matières.',
 E'## Conditions optimales\n\n| Paramètre | Valeur cible |\n|---|---|\n| Humidité grains | < 13% |\n| Humidité local | < 70% |\n| Température | < 25°C (zone ombre) |\n| Ventilation | Air libre |\n\n## Aménagement local de stockage\n\n1. **Sol bétonné** (pas terre battue = humidité)\n2. **Palettes bois** sous sacs (espace air 10-15 cm sol)\n3. **Espacement** entre piles de sacs (30-50 cm pour ventilation)\n4. **Ouvertures grillagées** anti-rongeurs/oiseaux\n5. **Toiture étanche** vérifiée chaque saison\n\n## Règle FIFO (First In, First Out)\n\n- **Premier entré, premier sorti**\n- Marquer date de réception sur chaque sac/lot\n- Ne JAMAIS empiler nouveau lot sur ancien\n\n## Lutte rongeurs\n\n- **Pièges mécaniques** (préférables aux raticides en élevage)\n- Si raticide : **boîtes appâts sécurisées**, jamais accessible aux porcs\n- Inspection hebdomadaire crottes/traces\n\n## Inspection régulière\n\n- **Visuelle 1x/semaine** : moisissures, échauffement, rongeurs\n- **Olfactive** : odeur de fermentation = problème\n- **Tactile** : sac chaud au toucher = humidité interne\n\n## Si sac infesté/moisi\n\n- **Isoler immédiatement**\n- Tester aflatoxines si maïs/arachide\n- Si > 20 ppb : **détruire** (incinérer, ne pas donner aux animaux)\n\n## Pertes types\n\n- Mauvais stockage : **10-20% des matières** = 50-100 000 FCFA/tonne perdue\n- Bon stockage : < 2% de pertes\n- **ROI investissement stockage = 6-12 mois**',
 ARRAY['stockage', 'humidite', 'fifo', 'rongeurs'],
 'FAO, CIRAD, IFIP'),

-- ========================================================
-- CONDUITE (10 tips)
-- ========================================================

('orientation-batiment-porcherie', 'Orientation bâtiment porcherie',
 'conduite', 'intermediaire',
 'En CI, orienter le bâtiment Est-Ouest pour minimiser exposition soleil. Façades longues au Nord et Sud, faîtière surélevée pour ventilation naturelle.',
 E'## Principe en climat tropical CI\n\n**Objectif** : minimiser la chaleur solaire directe + maximiser ventilation naturelle.\n\n## Orientation idéale\n\n```\n        NORD\n         ↑\n  [══════════════]  ← longueur du bâtiment\n  [               ]\n  [══════════════]\n         ↓\n        SUD\n```\n\n- **Axe longitudinal Est-Ouest** : seules les pignons (petits côtés) sont au Est et Ouest\n- **Façades longues** au Nord et au Sud : ombragées la plus grande partie de la journée\n- **Vent dominant** doit traverser le bâtiment perpendiculairement à l''axe\n\n## Pourquoi pas Nord-Sud ?\n\n- Soleil tape sur les façades longues toute la journée\n- Chaleur excessive en après-midi (côté Ouest brûle)\n- Pertes GMQ 5-15% en saison chaude\n\n## Aménagements thermiques\n\n### Toiture\n- **Isolation** sous tôle (laine de verre 5 cm OU faux plafond paille)\n- **Couleur claire** (blanc, gris) plutôt que noire\n- **Faîtière surélevée** (15-30 cm) = effet cheminée → évacuation air chaud\n- **Débord toiture** 1.5-2 m pour ombrer murs\n\n### Murs\n- **Hauteur basse murs** (60-80 cm pleins) puis claustra/grillage\n- **Plantations arbres ombrageants** : manguier, anacardier à 5-10 m\n\n### Ventilation\n- **Largeur bâtiment** ≤ 12 m pour ventilation transversale efficace\n- **Brumisateurs** ou aspersion toiture en pic chaleur (35°C+)\n\n## Coût indicatif\n\n- Bâtiment 10 truies basique : **3-5 M FCFA** (avec orientation correcte)\n- Reconvertir mauvaise orientation = ~30% surcoût pour palliatifs (clim, brumisation)',
 ARRAY['batiment', 'orientation', 'ventilation', 'climat'],
 'IFIP, CIRAD, FAO élevage tropical'),

('densite-animaux-m2', 'Densité animaux par m²',
 'conduite', 'debutant',
 'Densités cibles : porcelet sevré 0.3 m²/tête, croissance 0.6, finition 0.9, truie gestante 2.0, maternité 4.0.',
 E'## Tableau densités\n\n| Catégorie | m²/animal | Animaux/case 10 m² |\n|---|---|---|\n| Porcelet sevré (8-25 kg) | 0.3 | 33 |\n| Porc croissance (25-60 kg) | 0.6-0.7 | 14-16 |\n| Porc finition (60-110 kg) | 0.9-1.0 | 10-11 |\n| Truie gestante (groupe) | 2.0-2.5 | 4-5 |\n| Truie maternité (case) | 4-5 | 1 (+ porcelets) |\n| Verrat | 6-8 | 1 |\n\n## Conséquences sur-densité\n\n- **Bagarres** + lésions cutanées\n- **Stress** chronique → cortisol → baisse immunité\n- **GMQ -10 à -20%**\n- **IC dégradé** +0.2 à +0.3\n- **Caudo-cannibalisme** (queue, oreilles)\n\n## Conséquences sous-densité\n\n- **Coût construction** au m² surdimensionné\n- **Bâtiment plus difficile à chauffer/refroidir**\n- Animaux moins regroupés en hiver (impacts mineurs en CI)\n\n## Adaptation tropicale\n\nEn climat chaud CI, **monter de 10-15%** la densité recommandée pour favoriser dissipation chaleur entre animaux (paradoxal mais efficace dans certains designs).\n\nMais **toujours surveiller** : si toux/bagarres → trop dense.\n\n## Calcul ferme 50 truies\n\n- 50 truies × 4 m² maternité = 200 m² maternité (pic)\n- 50 × 2 portées × 10 porcs × 1 m² finition = 1 000 m² finition\n- + verrats, gestantes, sevrés...\n- **Total ~ 1 800-2 200 m² bâtiments**',
 ARRAY['densite', 'm2', 'logement', 'cases'],
 'IFIP, INRA, FAO'),

('conduite-en-bande-principe', 'Conduite en bande : principe et avantages',
 'conduite', 'intermediaire',
 'Conduite en bande = regrouper saillies sur 1 semaine, donc mises-bas, sevrages et ventes synchronisées. Optimise main-d''œuvre et vide sanitaire.',
 E'## Principe\n\nAu lieu de saillir au fil de l''eau, on **groupe les saillies sur 1 semaine** (la "bande"). Toutes les truies de la bande :\n- mettent bas la même semaine\n- sèvrent la même semaine\n- libèrent les cases la même semaine\n\n## Avantages\n\n1. **All-in / all-out** strict → vide sanitaire efficace → moins de maladies\n2. **Main-d''œuvre** : tâches groupées (vaccinations, pesées, tris)\n3. **Lots homogènes** à vendre → meilleur prix\n4. **Prévisibilité** : on sait combien de porcelets à J+114, j+135 (sevrage), j+170 (ventes)\n5. **Sécurité sanitaire** : pas de mélange d''âges → pas de transmission jeunes/vieux\n\n## Bandes courantes\n\n| Bandes | Truies/bande (pour 50 truies) | Rythme tâches |\n|---|---|---|\n| **7 jours** (hebdo) | 7 truies | Tâches chaque semaine |\n| **14 jours** (bi-mensuel) | 14 truies | Tâches tous les 15 j |\n| **21 jours** | 21 truies | Tâches tous les 3 sem |\n\n## Choix selon taille ferme\n\n- < 50 truies : bandes 14 ou 21 jours (intervalles plus longs)\n- 50-150 truies : bande hebdo (semaine) plus efficace\n- > 150 : bande hebdo ou continue\n\n## Mise en place\n\n1. **Synchronisation initiale** : altrenogest (Regumate) ou effet verrat groupé\n2. **Planning annuel** : tableau avec dates saillies, mises-bas, sevrages, ventes\n3. **Discipline rigoureuse** : ne pas saillir hors planning\n\n## Difficulté principale\n\n- Truie qui rate sa saillie → sortir de la bande ou retour 21 j (effort de re-synchronisation)\n- Investissement initial en synchronisation hormonale (3-5 000 FCFA/truie)',
 ARRAY['bande', 'conduite', 'organisation', 'vide-sanitaire'],
 'IFIP, INRA'),

('stress-thermique-mitiger', 'Stress thermique en CI : 7 mesures concrètes',
 'conduite', 'expert',
 'Au-delà de 28°C, le porc consomme -1 à -3% d''aliment par °C. Mitiger : brumisation, ventilation, eau fraîche, orientation bâtiment.',
 E'## Seuils critiques\n\n| Catégorie | Confort | Stress | Critique |\n|---|---|---|---|\n| Porcelet | 22-26°C | > 28 | > 32 |\n| Croissance | 18-22°C | > 25 | > 30 |\n| **Finition** | **15-20°C** | **> 24** | **> 28** |\n| Truie | 16-21°C | > 25 | > 30 |\n\n## Impact économique\n\n- À 30°C vs 22°C : **GMQ -25%**, IC +0.3, consommation -15%\n- Truie en lactation à 32°C : -2 kg aliment/j → -1 porcelet sevré\n\n## 7 mesures concrètes\n\n### 1. Orientation Est-Ouest (cf tip dédié)\n\n### 2. Toiture isolée + faîtière surélevée\n\n### 3. Ventilation naturelle\n- Largeur bâtiment ≤ 12 m\n- Ouvertures basses (entrée) et hautes (sortie)\n- Hauteur sous faîtage 3.5-4 m\n\n### 4. Brumisateurs\n- Sur le sol (pas directement sur porcs) — risque pneumonie\n- Mode pulsé : 30 sec ON / 5 min OFF\n- Active à T° > 28°C, RH < 70%\n- Conso eau : 0.3-0.5 L/porc/h\n\n### 5. Eau fraîche en abondance\n- Refroidir réservoir (zone ombre)\n- Eau < 22°C → +200 g consommation aliment/j\n\n### 6. Ventilateurs de plafond\n- Plus efficace que ventilateurs au sol\n- 1 ventilateur 80W / 30-50 m² de bâtiment\n- Conso : ~ 15-25 kWh/jour = 1 800-3 000 FCFA/jour\n\n### 7. Plantations ombrageantes\n- Manguiers, anacardiers, citronniers\n- À 5-10 m du bâtiment (pas trop près = humidité)\n- Bénéfice secondaire : fruits + lutte contre érosion\n\n## Astuce économique\n\n**Mouiller la toiture** en pic de chaleur (12-15h) avec un arroseur manuel ou automatique : baisse de 3-5°C intérieur.',
 ARRAY['stress-thermique', 'climatisation', 'brumisateurs', 'tropical'],
 'IFIP, CIRAD élevage tropical, FAO'),

('vide-sanitaire-protocole', 'Vide sanitaire entre bandes',
 'conduite', 'intermediaire',
 'Entre 2 bandes, vider le bâtiment, nettoyer haute pression, désinfecter, sécher 7-14 jours minimum. Étape clé biosécurité.',
 E'## Pourquoi c''est essentiel\n\n- **Casse les cycles** de pathogènes (parasites, bactéries, virus)\n- **Maladies courantes** (mycoplasme, E. coli) chutent de 50-80% avec vide sanitaire correct\n- **Croissance bande suivante** : +5-10% GMQ\n\n## Protocole en 5 étapes\n\n### 1. Sortie animaux (J0)\n- Vider toutes les cases\n- Identifier les animaux à réformer/vendre\n- Inspecter chaque case pour blessures, lésions à signaler\n\n### 2. Décapage gros (J0-J1)\n- Évacuer **toute la litière** + fumier\n- Démonter accessoires démontables\n- Brosser à sec\n\n### 3. Nettoyage haute pression (J1-J2)\n- **Eau + détergent alcalin** (soude diluée 1-2%)\n- Mouiller, laisser tremper 30 min, puis nettoyer\n- Toutes surfaces : sols, murs, plafonds, auges, tétines\n- Vérifier : aucune trace organique = nettoyage OK\n\n### 4. Désinfection (J2-J3)\n- **Désinfectant approprié** : glutaraldéhyde, formol 3%, ou peroxygène (Virkon, Oxypur)\n- Pulvérisateur basse pression\n- Respecter dose et temps de contact (15-30 min)\n- **Pédiluve renouvelé** à l''entrée\n\n### 5. Séchage (J3-J7+)\n- **Minimum 7 jours** secs avec aération max\n- Idéal : **14 jours** (élimine humidité résiduelle = ennemi des bactéries)\n- Vérifier : pas de flaques, sols secs au toucher\n\n## Coût\n\n- Détergent + désinfectant : ~5-15 000 FCFA / bâtiment 100 m²\n- Eau, main-d''œuvre : 1-2 j/personne\n- Pertes potentielles sans vide sanitaire : **50-200 000 FCFA** en mortalités + IC dégradé\n\n## Erreur fatale\n\n**Ne pas désinfecter** ou faire vide trop court (< 4 j) = perpétue les pathogènes. Bande suivante = mêmes problèmes.',
 ARRAY['vide-sanitaire', 'desinfection', 'biosecurite'],
 'IFIP, OIE, FAO'),

('tournee-matin-checklist', 'Tournée matin : checklist 10 points',
 'conduite', 'debutant',
 'Routine matinale : eau, aliment, comportement, mortalité, fèces, respiration, blessures, T° bâtiment, équipement, registre.',
 E'## Checklist tournée matin (30-60 min)\n\n### 1. Tour rapide bâtiments\n- Comptage rapide animaux\n- Détection morts/mourants\n\n### 2. Eau\n- Tous abreuvoirs fonctionnels (presser tétines)\n- Eau propre et fraîche\n- Niveau réservoir suffisant\n\n### 3. Aliment\n- Auges propres, pas d''aliment moisi\n- Reste de la veille = surveiller (refus = problème)\n- Distribution selon plan\n\n### 4. Comportement\n- Animaux qui se lèvent, vifs\n- Pas d''isolés dans un coin\n\n### 5. Mortalités\n- Sortir et noter : âge, cause apparente\n- Si plusieurs morts → alerte vétérinaire\n\n### 6. Fèces / urines\n- Couleur, consistance\n- Diarrhée groupée = signal d''alerte\n\n### 7. Respiration\n- Écouter : toux ?\n- Respiration accélérée (> 40/min) = fièvre\n\n### 8. Blessures / boiteries\n- Plaies fraîches, gonflements\n- Boiterie = isoler + traiter\n\n### 9. Environnement bâtiment\n- Température (thermomètre fixe) : 22-26°C porcelet, 18-22°C adulte\n- Ventilation OK ? Pas de courant d''air ?\n- Litière sèche\n\n### 10. Registre quotidien\n- Noter : date, observations, actions\n- Carnet d''élevage à jour\n\n## Routine soir (15-30 min)\n\n- Comptage + tour rapide\n- Distribution repas soir\n- Eau\n- Sécurisation (portes, lumières)\n\n## Erreurs débutants\n\n- Faire vite et ne pas observer\n- Ne pas noter les observations\n- Ne pas réagir aux signaux faibles',
 ARRAY['tournee', 'checklist', 'routine', 'observation'],
 'IFIP, INRA'),

('gmq-cible-par-stade', 'GMQ cibles par stade',
 'conduite', 'intermediaire',
 'GMQ (Gain Moyen Quotidien) : porcelet 250 g, sevré 400 g, croissance 700-800 g, finition 850-900 g.',
 E'## Cibles standards (race améliorée, conditions optimales)\n\n| Stade | Poids | GMQ cible | GMQ moyen CI |\n|---|---|---|---|\n| Naissance-Sevrage (0-28j) | 1.5 → 8 kg | 230-260 g | 200-230 |\n| Sevrage-25 kg (28-65j) | 8 → 25 kg | 400-500 g | 350-450 |\n| Croissance (25-60 kg) | 25 → 60 kg | 700-800 g | 600-700 |\n| Finition (60-110 kg) | 60 → 110 kg | 850-950 g | 750-850 |\n\n## Calcul pratique\n\n**GMQ = (Poids final - Poids initial) / Nb jours**\n\nExemple croissance :\n- Entrée à 8 kg, J28\n- Sortie à 25 kg, J70 (42 j de période)\n- **GMQ = (25 - 8) / 42 = 405 g/jour**\n\n## Facteurs influençant GMQ\n\n1. **Génétique** (lignée Large White / Landrace / Duroc / hybrides)\n2. **Alimentation** (qualité + quantité)\n3. **Eau** (souvent négligée)\n4. **Sanitaire** (animaux malades = GMQ ↓ 20-50%)\n5. **Température** (stress thermique ↓ 10-25%)\n6. **Densité** (sur-densité ↓ 10-15%)\n7. **Stress** (transports, mélanges = ↓ ponctuelle)\n\n## Impact économique GMQ\n\n**Améliorer GMQ croissance de 600 → 750 g/j :**\n- Période 25-60 kg : 47 j (au lieu de 58 j)\n- **Économie : 11 j × aliment 2 kg/j × 350 FCFA = 7 700 FCFA/porc**\n- Sur 50 porcs/cycle = **385 000 FCFA/cycle**\n\n## Mesure\n\n- **Pesées par bande** : entrée + sortie minimum\n- Idéal : pesées intermédiaires (toutes les 3-4 semaines)\n- Pèse-animaux : 50-150 000 FCFA',
 ARRAY['gmq', 'croissance', 'performance', 'indicateur'],
 'INRA, IFIP, NRC'),

('bien-etre-enrichissement', 'Bien-être : enrichissement environnemental',
 'conduite', 'intermediaire',
 'Enrichir l''environnement (jouets, paille, bois à mâcher) prévient le cannibalisme caudal. Pratique simple, ROI élevé.',
 E'## Pourquoi enrichir\n\n- Porc = animal **curieux et fouisseur** par nature\n- En case nue → s''attaque aux congénères (queue, oreilles)\n- Cannibalisme caudal coûte **2-5% mortalité** + dévaluation carcasses\n\n## Niveaux d''enrichissement\n\n### Niveau 1 — basique (gratuit ou peu cher)\n- **Paille fraîche** dans la case (1-2x/semaine)\n- **Bois dur à mâcher** suspendu (acacia, palmier)\n- **Sacs de jute** suspendus\n- **Boules ou chaînes** en plastique dur\n\n### Niveau 2 — moyen\n- **Tubes en bois** rotatifs\n- **Mangeoires de fouille** avec terre ou son\n- **Aire d''exercice** extérieure (parc plein air)\n\n### Niveau 3 — premium (élevages bio/bien-être labellisés)\n- Sol paillé épais\n- Cours d''exercice\n- Brossage automatique\n- Musique d''ambiance\n\n## Règles d''or\n\n1. **Renouvellement** : changer ou refresh régulièrement (curiosité s''émousse)\n2. **Adaptation à l''âge** : porcelets aiment textures molles, adultes objets durs\n3. **Sécurité** : pas de petits objets ingérables, pas de cordes nylon (étouffement)\n4. **Hygiène** : enlever et nettoyer objets souillés\n\n## ROI\n\n- Coût enrichissement : **0-500 FCFA/case/mois**\n- Réduction cannibalisme : -3-5% mortalité\n- Sur 100 porcs : 3-5 porcs sauvés × 50 000 FCFA = **150-250 000 FCFA**\n\n## Au-delà du ROI\n\n- Animaux moins stressés = meilleure conversion alimentaire\n- Image éthique de la ferme (export, vente directe)\n- Conditions de travail (animaux calmes = personnel moins stressé)',
 ARRAY['bien-etre', 'enrichissement', 'cannibalisme', 'jouets'],
 'EFSA, IFIP, INRA'),

('mortalite-seuils-acceptables', 'Mortalité : seuils acceptables et alertes',
 'conduite', 'expert',
 'Mortalité acceptable : néonatale 8-10%, sevrage 2-3%, post-sevrage 2-3%, engraissement 2-3%. Total naissance-abattage < 15%.',
 E'## Seuils par stade\n\n| Stade | Mortalité acceptable | Alerte |\n|---|---|---|\n| **Néonatale (0-3 j)** | 5-8% | > 10% |\n| 3-21 j (lactation) | 2-3% | > 5% |\n| Sevrage-25 kg | 2-3% | > 5% |\n| Croissance (25-60 kg) | 1-2% | > 3% |\n| Finition (60-110 kg) | 1-2% | > 3% |\n| **Total naissance-abattage** | **10-15%** | **> 20%** |\n\n## Causes principales par stade\n\n### Néonatale\n- Écrasement maternel (40-50%)\n- Hypothermie\n- Hypoglycémie / faim\n- Colostrum insuffisant\n- Malformations\n\n### Lactation\n- Colibacillose néonatale\n- Coccidiose\n- Anémie\n\n### Sevrage\n- E. coli post-sevrage\n- Streptococcie\n- Choc alimentaire/thermique\n\n### Engraissement\n- Mycoplasmose / pneumonie\n- Salmonelloses\n- Boiteries\n- Stress thermique\n\n## Démarche en cas de mortalité élevée\n\n1. **Autopsie immédiate** (idéalement vétérinaire)\n2. **Photo lésions** internes\n3. **Comptage par âge + bâtiment** (carte chaud)\n4. **Prélèvements** si suspicion bactérienne/virale\n5. **Revue du planning** : changement aliment ? introduction nouvelle bande ?\n\n## Tableau de bord mortalité\n\n- Suivi **hebdomadaire** : nb morts / nb animaux\n- Graphique mensuel\n- Seuil d''alerte : ferme + 50% vs moyenne 6 mois\n- **Investigation systématique** si dépassement',
 ARRAY['mortalite', 'seuils', 'kpi', 'autopsie'],
 'IFIP, INRA, BIPORC'),

('all-in-all-out', 'All-in / All-out : règle d''or',
 'conduite', 'intermediaire',
 'All-in/all-out = entrer tous les animaux d''une bande ensemble, les sortir ensemble, vide sanitaire complet. Baisse mortalité de 30-50%.',
 E'## Principe\n\nÀ chaque cycle d''un bâtiment :\n1. **Entrée groupée** : tous les animaux entrent le même jour (ou semaine)\n2. **Cycle commun** : ils vivent ensemble la phase complète (sevrage, croissance, etc.)\n3. **Sortie groupée** : tous partent le même jour\n4. **Vide sanitaire** : nettoyage + désinfection + séchage avant nouvelle bande\n\n## Avantages\n\n- **Casse cycles pathogènes** entre bandes\n- **Mortalité baisse 30-50%**\n- **GMQ +5-10%** (animaux homogènes = compétition équilibrée)\n- **IC amélioré** de 0.1-0.2\n- **Vente groupée** = meilleur prix\n- **Vide sanitaire efficace**\n\n## Inconvénients\n\n- **Planification rigoureuse** indispensable\n- **Bâtiments dimensionnés** pour le pic\n- **Souplesse réduite** (ajustements difficiles)\n\n## Conditions de réussite\n\n### Bâtiments dédiés par phase\n- Maternité ≠ Sevrage ≠ Engraissement\n- Pas de mélange d''âges dans un même bâtiment\n\n### Bandes synchronisées\n- Saillies sur 1 semaine (cf tip conduite-en-bande)\n- Calendrier annuel respecté strictement\n\n### Vide sanitaire 7-14 j minimum\n- Cf tip vide-sanitaire-protocole\n\n## Erreurs courantes\n\n1. **Mélanger des âges** "pour gagner de la place" → ruine le principe\n2. **Vider sans désinfecter** → pas de bénéfice\n3. **Bandes désynchronisées** → impossible all-in/all-out réel\n4. **Bâtiments multi-usages** sans cloison → cycles cassés\n\n## Continu vs All-in/all-out\n\n| Critère | Continu | All-in/all-out |\n|---|---|---|\n| Investissement | Faible | Plus élevé (modulable) |\n| Mortalité | 15-25% | 10-15% |\n| Productivité | 18-22 porcelets/truie/an | 22-26 |\n| Souplesse | +++ | + |\n| ROI long terme | Moyen | Excellent |',
 ARRAY['all-in-all-out', 'bande', 'biosecurite', 'organisation'],
 'IFIP, INRA, OIE'),

-- ========================================================
-- ÉCONOMIQUE (10 tips)
-- ========================================================

('cout-production-porc-decomposition', 'Coût production porc : décomposition',
 'economique', 'intermediaire',
 'Sur 100 FCFA de coût total : aliment 65-75%, main-d''œuvre 10%, sanitaire 5%, amortissements 8%, divers 7%.',
 E'## Répartition coûts standards\n\n| Poste | Part | FCFA/kg vif (cible 1 200-1 400) |\n|---|---|---|\n| **Aliment** | 65-75% | 850-1 000 |\n| Main-d''œuvre | 8-12% | 100-150 |\n| Sanitaire (vaccins, vétérinaire) | 4-6% | 50-80 |\n| Amortissements bâtiment + équipement | 6-10% | 80-120 |\n| Énergie (élec, eau) | 2-4% | 30-50 |\n| Reproducteurs (achat + amortissement) | 3-5% | 40-60 |\n| Divers (transport, frais) | 2-4% | 30-50 |\n| **TOTAL** | **100%** | **1 200-1 400** |\n\n## Cible vente porc CI 2025\n\n- **Prix vente vif** : 1 500-1 800 FCFA/kg\n- **Coût production** : 1 200-1 400\n- **Marge brute** : 100-400 FCFA/kg = ~10-25%\n\n## Levier prioritaire = ALIMENT\n\nRéduire de 10% le coût aliment = baisse 7% du coût total.\n\n### Comment ?\n\n1. **Formuler maison** (vs concentré industriel) : -30 à -40%\n2. **Achat groupé** ou en récolte (sept-déc) : -10 à -15%\n3. **Substitutions** (manioc, son riz) : -5 à -10%\n4. **Réduction gaspillage** (auges adaptées) : -3 à -5%\n5. **IC amélioré** (génétique + santé) : -5 à -10%\n\n## Tableau de bord coût\n\nSuivre **mensuel** :\n- Coût aliment / kg vif produit\n- Coût total / porc abattu\n- Marge brute / porc\n- Trésorerie\n\n## Erreurs à éviter\n\n- **Sous-estimer** main-d''œuvre (même si famille)\n- **Oublier** amortissements\n- **Pas de comptabilité** régulière',
 ARRAY['cout-production', 'budget', 'aliment', 'marge'],
 'IFIP, BIPORC, FAO'),

('prix-porc-vif-marche-ci', 'Prix du porc vif marché CI 2025',
 'economique', 'debutant',
 'Prix indicatifs 2025 : porc vif 1 500-1 800 FCFA/kg, porcelet sevré 35-50 000 FCFA, truie réforme 200-300 000 FCFA.',
 E'## Prix de référence marché CI 2025\n\n*(Indicatifs, à actualiser localement)*\n\n### Porc à l''abattage\n- **Porc vif (100-110 kg)** : 1 500-1 800 FCFA/kg = 150-200 000 FCFA/animal\n- **Carcasse (75 kg)** : 2 200-2 600 FCFA/kg\n- **Découpe détaillée** : 3 000-4 500 FCFA/kg\n\n### Reproducteurs\n- **Porcelet sevré (8-10 kg)** : 35-50 000 FCFA\n- **Cochette prête à saillir (130 kg)** : 250-350 000 FCFA\n- **Verrat reproducteur** : 400-700 000 FCFA\n- **Truie réformée** : 200-300 000 FCFA (selon état)\n\n## Saisonnalité\n\n| Période | Demande | Prix |\n|---|---|---|\n| **Tabaski/Aïd** (variable) | ↗↗↗ | +15-20% |\n| **Noël** (déc) | ↗↗ | +10-15% |\n| **Pâques** (mars-avril) | ↗ | +5-10% |\n| **Rentrée scolaire** (sept) | → | normal |\n| **Saison pluies** (juin-août) | → | normal-baisse |\n| **Carême** (40j avant Pâques) | ↘ | -5-10% (porc évité chrétiens) |\n\n## Canaux de distribution\n\n### Vente directe ferme\n- Marge max : pas d''intermédiaire\n- Volume limité\n- Prix : ~ 80-90% prix gros\n\n### Abattoirs (SIPRA, SIVAC)\n- Volumes garantis\n- Prix fixés (négociable un peu)\n- Délai paiement 15-30 j\n- Norme qualité\n\n### Grossistes / restaurateurs\n- Prix intermédiaire\n- Régularité de commande\n- Négociation possible\n\n### Marché informel\n- Prix variables\n- Risque trésorerie (paiement comptant pas garanti)\n\n## Stratégie\n\n**Vendre 70% via canaux formels** (récurrence, trésorerie) + 30% direct/vente détaillée (marge).',
 ARRAY['prix', 'marche', 'vente', 'fcfa'],
 'BIPORC, MIRAH, marché CI 2025'),

-- (continuation des 8 tips économique restants en version plus compacte)

('seuil-rentabilite-calcul', 'Seuil de rentabilité élevage porcin',
 'economique', 'expert',
 'Seuil de rentabilité = charges fixes / marge unitaire. Pour 20 truies, atteindre 350-400 porcs vendus/an pour couvrir charges.',
 E'## Formule\n\n**Seuil de rentabilité (SR) = Charges fixes annuelles / Marge unitaire par porc**\n\n## Exemple ferme 20 truies\n\n### Charges fixes annuelles\n- Amortissement bâtiments : 1 200 000 FCFA\n- Main-d''œuvre fixe : 1 800 000 FCFA\n- Énergie, eau : 400 000 FCFA\n- Vétérinaire forfait : 300 000 FCFA\n- Frais divers : 300 000\n- **Total CF : 4 000 000 FCFA/an**\n\n### Marge unitaire\n- Prix vente porc : 175 000 FCFA\n- Coût variable (aliment, sanitaire, semence) : 165 000 FCFA\n- **Marge unitaire : 10 000 FCFA/porc**\n\n### Calcul SR\n**SR = 4 000 000 / 10 000 = 400 porcs/an**\n\n## Productivité 20 truies\n\n- 20 truies × 2 portées × 9 porcelets sevrés = **360 porcs/an**\n- Production < SR → **pertes**\n\n## Améliorer la situation\n\n1. **Augmenter productivité** : 22 porcelets/truie/an au lieu de 18 → 440 porcs\n2. **Baisser coûts variables** : aliment maison → marge unitaire monte à 15 000 → SR descend à 267\n3. **Combiner les 2** : marge 15K + 440 porcs = **2 600 000 FCFA bénéfice**\n\n## Le piège des petites fermes\n\n- < 15 truies : très difficile d''atteindre SR\n- **Mini viable** : 20-30 truies en CI 2025',
 ARRAY['rentabilite', 'seuil', 'calcul', 'fixe-variable'],
 'IFIP, BIPORC, MIRAH'),

('marge-brute-calcul', 'Marge brute / porc : calcul et cible',
 'economique', 'intermediaire',
 'Marge brute = Prix vente - Coûts variables. Cible : 15-25 000 FCFA/porc. Si < 10 000, alerte rentabilité.',
 E'## Calcul\n\n**MB = Prix vente porc - Coûts variables**\n\nCoûts variables = aliment + sanitaire + semence + transport vers abattoir\n\n## Exemple porc 100 kg\n\n| Poste | FCFA |\n|---|---|\n| Prix vente vif 1 600 × 100 | 160 000 |\n| Aliment naissance-abattage (~300 kg × 350) | -105 000 |\n| Sanitaire (vaccins, vermifuges, antibio) | -8 000 |\n| Part semence (IA) | -2 000 |\n| Transport / abattoir | -3 000 |\n| **Marge brute** | **+42 000** |\n\n## Cibles\n\n| Situation | MB/porc |\n|---|---|\n| Excellente | > 30 000 |\n| **Bonne** | **15-30 000** |\n| Limite | 5-15 000 |\n| Pertes | < 5 000 |\n\n## Leviers d''amélioration\n\n### Côté revenus\n- **Vente directe** : +10-15% prix\n- **Saison favorable** (Noël, Tabaski) : +15-20%\n- **Qualité label** ou bio : +20-30%\n\n### Côté coûts\n- **Aliment maison** vs industriel : -30-40% sur le poste aliment\n- **Vaccinations préventives** : économies vétérinaire\n- **IA partagée** entre fermes : -50% coût semence\n\n## Tableau de bord\n\nSuivi mensuel ou trimestriel :\n- MB moyenne par porc abattu\n- Tendance vs 6 mois précédents\n- Comparaison vs ferme similaire (benchmark)',
 ARRAY['marge-brute', 'rentabilite', 'kpi'],
 'IFIP, BIPORC'),

('plan-tresorerie-eleveur', 'Plan de trésorerie : indispensable',
 'economique', 'intermediaire',
 'Plan de trésorerie mensuel = entrées (ventes) - sorties (aliment, sanitaire, salaires, etc.). Anticiper les creux saisonniers.',
 E'## Pourquoi c''est crucial\n\n- **Élevage = cycles longs** : 6 mois entre saillie et vente\n- **Cash flow négatif** au démarrage (achats reproducteurs + bâtiment) jusqu''à 12-18 mois\n- Mauvaise trésorerie = arrêt approvisionnement → famine porcs → catastrophe\n\n## Modèle simple plan trésorerie mensuel\n\n```\nMois            | Jan | Fév | Mar | Avr | Mai | ...\nVentes porcs    | 1.5M| 0   | 1.8M| 0   | 2.0M|\nVentes truies   | 0   | 200K| 0   | 0   | 0   |\nTotal entrées   | 1.5M| 200K| 1.8M| 0   | 2.0M|\n----\nAliment         | 800K| 800K| 850K| 850K| 800K|\nSanitaire       | 50K | 100K| 50K | 80K | 50K |\nSalaires        | 250K| 250K| 250K| 250K| 250K|\nÉnergie + eau   | 80K | 80K | 80K | 80K | 80K |\nDivers          | 50K | 50K | 50K | 50K | 50K |\nTotal sorties   | 1.2M| 1.3M| 1.3M| 1.3M| 1.2M|\n----\nSolde mois      | +300| -1.1M| +500| -1.3M| +800|\nSolde cumulé    | +300| -800K| -300K| -1.6M| -800K|\n```\n\n## Lecture\n\n- **Solde cumulé négatif** = besoin de cash (épargne, crédit, découvert)\n- **Anticipation 3 mois** minimum\n- **Pic difficulté** : Avril (1.6M négatif) → prévoir réserve\n\n## Outils\n\n- Excel/Google Sheets simple\n- App comptabilité : Sage, Ciel\n- Pour démarrage : carnet papier avec colonnes\n\n## Mises à jour\n\n- **1x/semaine** noter recettes/dépenses\n- **1x/mois** clôturer + projeter 3 mois\n- **1x/trimestre** analyser écarts vs prévisions',
 ARRAY['tresorerie', 'cash-flow', 'gestion'],
 'CCI-CI, FIRCA, OHADA'),

('financement-microfinance-ci', 'Financement élevage : microfinance CI',
 'economique', 'intermediaire',
 'Microfinance accessible : Coopec, RCMEC, Advans. Taux 12-18%/an. Banques (BICICI, Ecobank) plus difficiles d''accès pour petits éleveurs.',
 E'## Acteurs financiers en CI\n\n### Microfinance (accessibles)\n- **Coopec** (Coopératives d''épargne et de crédit) : présence rurale forte\n- **RCMEC** : forte présence agritech\n- **Advans CI** : prêts agricoles dédiés\n- **PAMF** (Premier Agence Microfinance)\n- **GTI** (Groupe TGI)\n\n### Banques classiques (plus difficiles)\n- BICICI, Ecobank, NSIA, Société Générale\n- Garanties exigées (foncier, caution)\n- Taux : 8-12% mais conditions restrictives\n\n## Taux indicatifs 2025\n\n| Institution | Taux annuel | Montant max |\n|---|---|---|\n| Microfinance | 12-18% | 5-50 M |\n| Banque commerciale | 8-12% | > 20 M |\n| FIRCA (subvention) | 0-3% | 5-30 M |\n\n## FIRCA (Fonds Interprofessionnel pour la Recherche et le Conseil Agricoles)\n\n- Subventions et prêts bonifiés\n- Filière porcine éligible\n- Conditions : projet structuré, formation, suivi\n- Site : firca.ci\n\n## Documents pour dossier crédit\n\n1. **Pièces identité** (CNI, registre commerce)\n2. **Plan d''affaires** (3-5 ans)\n3. **Compte d''exploitation prévisionnel**\n4. **Garanties** : foncier (titre/permis occuper), caution solidaire, gage matériel\n5. **Devis bâtiments + équipements**\n6. **Historique** d''activité si déjà en cours\n\n## Astuce\n\n- **Démarrer petit avec fonds propres** (5 truies) puis financer extension\n- **Coopérative** d''éleveurs porcins : pouvoir négociation meilleure\n- **Garantie groupée** entre 5-10 éleveurs : moins de risque pour la banque\n\n## Éviter\n\n- Taux > 25% (usuraires)\n- Engagements trop courts (< 24 mois pour porc)\n- Garanties personnelles (maison familiale)',
 ARRAY['financement', 'credit', 'microfinance', 'firca'],
 'BCEAO, MIRAH, FIRCA'),

('vente-directe-marges', 'Vente directe vs grossiste',
 'economique', 'debutant',
 'Vente directe = +20-30% prix mais effort commercial. Grossiste/abattoir = volumes garantis, marge réduite mais récurrence.',
 E'## Comparaison\n\n| Critère | Vente directe | Grossiste/Abattoir |\n|---|---|---|\n| **Prix** | 1 800-2 500 FCFA/kg | 1 400-1 700 |\n| **Marge** | Très élevée | Moyenne |\n| **Volume** | Limité (~10-30 porcs/mois) | Élevé (100+) |\n| **Temps** | Beaucoup (livraisons, négos) | Peu |\n| **Trésorerie** | Comptant | Paiement 15-45 j |\n| **Régularité** | Variable | Garantie |\n| **Risques** | Stock invendu | Aucun |\n\n## Stratégie mixte recommandée\n\n**70% grossiste + 30% direct** = équilibre revenus/marges\n\n## Vente directe — canaux\n\n### 1. Vente à la ferme\n- Cible : restaurateurs, traiteurs locaux\n- Prix : 1 800-2 200 FCFA/kg vif\n- Effort : ouverture programmée 1-2j/sem\n\n### 2. Marchés / kiosques fixes\n- Cible : particuliers\n- Marge maximale (3 000+ FCFA/kg en détaillé)\n- Investissement : kiosque + frigo + boucher\n\n### 3. Restauration\n- Contrat mensuel restaurants, maquis\n- Prix négocié : 1 700-2 000 FCFA/kg\n- Régularité : 2-3 porcs/sem\n\n### 4. Vente en ligne (émergent)\n- Réseaux sociaux + WhatsApp\n- Livraison Abidjan : marges premium\n- Investissement : photos, communication\n\n## Construire une clientèle\n\n1. **Qualité constante** (race, alimentation, durée engraissement)\n2. **Marque/identité** (logo, nom de ferme)\n3. **Bouche-à-oreille** : satisfaction = recommandation\n4. **Présence visible** : panneau ferme, carte de visite\n\n## Investissement vente directe\n\n- Kiosque urbain : **2-5 M FCFA**\n- Équipement (frigo, balance, billot) : **500 K - 1 M**\n- ROI : 18-36 mois si volumes maintenus',
 ARRAY['vente-directe', 'marge', 'commercial'],
 'CGECI, BIPORC'),

-- ========================================================
-- INSTALLATION (10 tips)
-- ========================================================

('budget-demarrage-10-truies', 'Budget démarrage 10 truies CI',
 'installation', 'debutant',
 'Budget complet 10 truies en CI : 5-8 M FCFA. Bâtiments 50%, reproducteurs 20%, équipement 15%, fonds roulement 15%.',
 E'## Estimation budget (CI 2025, terrain non inclus)\n\n### Bâtiments (~50% du total)\n- Porcherie 10 truies + maternité + engraissement (~150 m²) : **2 500 000 FCFA**\n- Mur, clôture, sas sanitaire : **500 000**\n- Adduction eau (forage ou raccord) : **400 000**\n- Électrification (solaire 1.5 kWc ou raccord) : **600 000**\n- **Total bâtiments : ~ 4 000 000 FCFA**\n\n### Reproducteurs (~20%)\n- 10 cochettes prêtes saillie × 250 000 : **2 500 000**\n- 1 verrat 500 000 (ou opter IA) : **500 000**\n- (Ou kit IA + 50 doses semence × 5 000 : **250 000**)\n- **Total reproducteurs : ~ 2 750 000 (avec verrat) ou 1 500 000 (IA)**\n\n### Équipement (~15%)\n- Auges, abreuvoirs : **200 000**\n- Lampes chauffantes (4) : **150 000**\n- Pèse-animaux + thermomètre : **100 000**\n- Pulvérisateur, brosses, seaux : **80 000**\n- Trousse premiers soins : **70 000**\n- **Total équipement : ~ 600 000**\n\n### Fonds de roulement 3 premiers mois (~15%)\n- Aliment 3 mois : **800 000**\n- Vétérinaire + vaccins : **150 000**\n- Salaire 1 ouvrier × 3 mois : **300 000**\n- Énergie, eau, divers : **150 000**\n- **Total fonds roulement : ~ 1 400 000**\n\n## TOTAL\n\n**5,5 à 8 M FCFA** selon options et négociations\n\n## Cash flow attendu\n\n- **Mois 1-6** : 100% sorties (investissement + nourrissage gestantes)\n- **Mois 7-9** : premières mises-bas, peu de ventes\n- **Mois 12-14** : premières ventes porcs engraissés\n- **Mois 18** : régime de croisière\n- **Retour sur investissement : 4-6 ans**\n\n## Erreurs à éviter\n\n1. **Sous-budget fonds roulement** → manque cash pendant 6 mois\n2. **Bâtiments trop grands** "pour plus tard" → amortissement écrasant\n3. **Importer reproducteurs sans préparation** → mortalité au transport',
 ARRAY['budget', 'demarrage', 'investissement', 'roi'],
 'FIRCA, MIRAH, BIPORC CI'),

('choix-race-porc-ci', 'Choisir une race adaptée CI',
 'installation', 'intermediaire',
 'Large White + Landrace + Duroc = standards CI (croissance rapide). Races locales (Ashanti Dwarf, Bakossi) = rustiques mais lentes.',
 E'## Races commerciales (croissance optimisée)\n\n### Large White\n- **Origine** : Royaume-Uni\n- **Profil** : truie excellente (12-14 porcelets/portée), bon allaitement\n- **GMQ adulte** : 750-900 g\n- **Disponibilité CI** : élevée (verraterie locale)\n- **Idéal pour** : amélioration de lignée femelle\n\n### Landrace\n- **Origine** : Danemark/Suède\n- **Profil** : très prolifique (13-15 porcelets), corps allongé\n- **GMQ** : 750-850 g\n- **Disponibilité** : moyenne (importation)\n- **Idéal pour** : truies en élevage intensif\n\n### Duroc\n- **Origine** : États-Unis\n- **Profil** : rusticité, qualité viande supérieure (persillé)\n- **GMQ** : 800-950 g (le meilleur)\n- **Disponibilité** : moyenne\n- **Idéal pour** : verrat terminal (croisement avec LW × Landrace)\n\n### Pietrain\n- **Origine** : Belgique\n- **Profil** : musculaire (rendement carcasse élevé)\n- **GMQ** : 750-850 g (mais sensible stress)\n- **Disponibilité CI** : faible\n- **Idéal pour** : verrat terminal, marché viande maigre\n\n## Schéma croisement classique\n\n```\nTruie [Large White × Landrace] = F1 (très prolifique)\n   × \nVerrat Duroc ou Pietrain\n   = Porcs engraissement (croissance + qualité)\n```\n\n## Races locales africaines\n\n### Ashanti Dwarf, Bakossi\n- **Avantages** : rusticité, résistance pathologies tropicales, faibles besoins\n- **Inconvénients** : petite taille adulte (50-70 kg), portée réduite (6-8), croissance lente\n- **Niche** : élevage extensif rural, marchés traditionnels\n\n### Mix race exotique × locale\n- **Croisement F1** : compromis croissance/rusticité\n- Intéressant pour démarrage avec moyens limités\n\n## Recommandation pour démarrer en CI\n\n**Pour ferme commerciale moderne** : Large White × Landrace + verrat Duroc.\n**Pour ferme rurale autonomie** : F1 (race exotique × locale).\n\n## Où acheter\n\n- **Verraterie de l''État (MIRAH)** : reproducteurs certifiés\n- **Fermes membres BIPORC**\n- **Importation Burkina, Ghana** (génétique disponible)\n- ⚠️ Importation = quarantaine + tests sérologiques obligatoires',
 ARRAY['race', 'large-white', 'landrace', 'duroc', 'croisement'],
 'MIRAH, BIPORC, FAO'),

('plan-ferme-10-truies', 'Plan ferme porcine 10 truies',
 'installation', 'intermediaire',
 'Ferme 10 truies = ~150 m² bâtiments : maternité (30 m²), gestation (40 m²), porcelets sevrés (30 m²), engraissement (50 m²).',
 E'## Calcul surface besoin\n\n### Maternité\n- 10 truies × 2 portées/an = 20 mises-bas/an\n- À tout moment : ~2-3 truies en maternité simultanément\n- **3 cases × 4 m² = 12 m² maternité**\n- + circulation + sas = **30 m² total**\n\n### Gestation\n- 10 truies + 1-2 cochettes en attente\n- **Groupe : 12 × 2 m² = 24 m²**\n- + circulation = **40 m² total**\n\n### Verrat (ou stockage IA)\n- 1 case verrat : 6-8 m²\n- **10 m² avec circulation**\n\n### Porcelets sevrés (8-25 kg)\n- 20 porcelets/portée × 3 portées simultanées = 60 porcelets\n- 60 × 0.3 m² = 18 m²\n- **30 m² avec circulation**\n\n### Croissance/Finition\n- 30-50 porcs simultanément\n- 50 × 1 m² = 50 m²\n- **50-60 m² avec circulation**\n\n### **TOTAL : 160-170 m² bâtis**\n\n## Plan schématique\n\n```\n                  Entrée ↓\n              ┌─[SAS sanitaire]\n              │\n   ┌──────────┴──────────┐\n   │     Gestation       │ 40 m²\n   │  (10 truies vides)  │\n   └──────────┬──────────┘\n              │\n   ┌──────────┴──────────┐\n   │   Maternité (3 cases)│ 30 m²\n   └──────────┬──────────┘\n              │\n   ┌──────────┴──────────┐\n   │  Porcelets sevrés   │ 30 m²\n   └──────────┬──────────┘\n              │\n   ┌──────────┴──────────┐\n   │  Engraissement      │ 50 m²\n   └─────────────────────┘\n              ↓\n          [Vente]\n```\n\n## Points d''attention\n\n- **Pente du sol** 2-3% pour évacuation urines/eaux\n- **Orientation Est-Ouest** (cf tip conduite)\n- **Drainage** autour du bâtiment\n- **Espace fumier** ~ 20 m² séparé\n- **Stockage aliment** : 15-20 m² (ventilé, surélevé)\n\n## Coût construction CI 2025\n\n- Matériaux locaux + travail simple : **15-20 000 FCFA/m²**\n- **Total bâtiments 10 truies : 2,5-3,5 M FCFA**',
 ARRAY['plan-ferme', 'batiment', 'dimensionnement', 'm2'],
 'IFIP, FAO, IRAT'),

('panneaux-solaires-eleveur', 'Panneaux solaires : électrifier la ferme',
 'installation', 'intermediaire',
 'Installation solaire 1.5-3 kWc couvre besoins ferme 10-20 truies : éclairage, pompage, lampes chauffantes. ROI 4-6 ans en CI.',
 E'## Besoins électriques porcherie\n\n### Petite ferme 10 truies\n- **Éclairage** LED : 200-300 W\n- **Pompage eau** (forage 50 m) : 600-800 W intermittent\n- **Lampes chauffantes porcelets** (3) : 150-250 W chacune × 8h/j hiver\n- **Ventilateurs** : 100-300 W intermittent\n- **Brumisateurs** : 50-150 W intermittent\n- **Réfrigérateur** (vaccins, semence) : 100-150 W\n\n**Consommation moyenne : 4-8 kWh/jour**\n\n## Installation type 1.5 kWc\n\n### Composants\n- **5-6 panneaux solaires** 300 W (~ 1.5 kWc total)\n- **Onduleur hybride** 2-3 kW\n- **Batteries lithium** 5 kWh (autonomie 1 jour)\n- **Structure de fixation**, câblage, protections\n\n### Coût CI 2025\n- Kit complet 1.5 kWc + batteries : **1.5-2.5 M FCFA**\n- Kit 3 kWc + batteries : **2.5-4 M**\n- Pose locale : 200-400 000\n\n### Production journalière (CI ensoleillement ~ 5h équivalent)\n- 1.5 kWc → **7-8 kWh/jour**\n- Couvre largement ferme 10 truies\n\n## Comparaison vs raccordement CIE\n\n| Critère | Solaire | CIE (réseau) |\n|---|---|---|\n| Investissement | 2-3 M | 200-500 K raccord + ~30 000/mois |\n| Coût mensuel | 0 (entretien batteries 5 ans) | 25-50 000 FCFA |\n| Coupures | Aucune | Fréquentes en CI rurale |\n| Coût 10 ans | 2-3 M | 3-6 M |\n\n**ROI solaire : 4-6 ans**\n\n## Avantages stratégiques\n\n- **Autonomie totale** (pas de coupures)\n- **Refroidissement vaccins** garanti\n- **Pompage eau** sécurisé (vital)\n- **Image moderne** de la ferme\n- **Subventions FIRCA** parfois disponibles (énergie verte)\n\n## Installateurs solaires CI 2025\n\n- Helios CI, Solar23, Greenwish, Mobisol, Sun Capital\n- ⚠️ Demander 3 devis comparatifs\n- Garantie 10-25 ans sur panneaux exigée',
 ARRAY['solaire', 'electrification', 'autonomie', 'investissement'],
 'AGER, ANARE-CI'),

('autorisations-administratives-ci', 'Autorisations administratives élevage porcin CI',
 'installation', 'expert',
 'Démarches : autorisation MIRAH (préfectorale), permis construire, déclaration ICPE, certificat sanitaire, immatriculation entreprise.',
 E'## Démarches obligatoires en CI\n\n### 1. Immatriculation entreprise\n- **CEPICI** : Centre de Promotion des Investissements\n- Statut : entreprise individuelle, SARL, coopérative\n- Coût : 25-100 000 FCFA selon statut\n- Délai : 1-2 semaines\n\n### 2. Autorisation MIRAH (préfectorale)\n- **Ministère des Ressources Animales et Halieutiques**\n- Autorisation d''exploitation d''élevage\n- Dossier : plan ferme, statut, attestation foncière\n- Coût : ~50 000 FCFA\n- Délai : 1-3 mois\n\n### 3. Permis de construire\n- **Mairie de la commune**\n- Pour tout bâtiment > 50 m²\n- Plan architectural + autorisation préfectorale\n- Coût : variable (50-200 000)\n- Délai : 1-3 mois\n\n### 4. Déclaration ICPE (Installation Classée)\n- Si > 50 truies ou > 200 porcs engraissement\n- **Direction de l''Environnement**\n- Étude impact environnemental\n- Coût : 500 K - 2 M selon taille\n\n### 5. Certificat sanitaire\n- **Vétérinaire MIRAH** : attestation conformité bâtiments\n- Préalable à l''exploitation\n- Inspection sur place\n\n### 6. Carte d''éleveur professionnel (optionnel)\n- Délivrée par MIRAH ou BIPORC\n- Permet accès subventions FIRCA\n\n## Calendrier type\n\n| Étape | Mois |\n|---|---|\n| Création entreprise CEPICI | M1 |\n| Étude foncière + acquisition | M1-M2 |\n| Plan ferme + permis construire | M2-M4 |\n| Autorisation MIRAH | M3-M5 |\n| Construction | M5-M9 |\n| Certificat sanitaire (inspection) | M9 |\n| **Démarrage exploitation** | **M10** |\n\n## Coûts cumulés administratifs\n\n**Total démarches : 250 K - 1 M FCFA** (selon taille projet)\n\n## Conseils\n\n1. **Commencer par CEPICI** (entreprise existante facilite tout)\n2. **Solliciter conseiller agritech FIRCA** (gratuit, accompagnement)\n3. **Ne pas démarrer sans certificat sanitaire** = saisie possible\n4. **Adhérer à BIPORC** (Bureau Interprofessionnel Porcin) = poids collectif',
 ARRAY['autorisations', 'mirah', 'cepici', 'permis', 'reglementaire'],
 'MIRAH, CEPICI, FIRCA, BIPORC'),

('equipement-liste-minimum', 'Liste équipement minimum 10 truies',
 'installation', 'debutant',
 'Équipement de base ferme 10 truies : auges, abreuvoirs, lampes chauffantes, balance, thermomètre, trousse soin, outillage. Budget 500-800 000.',
 E'## Auges et abreuvoirs\n\n### Auges\n- **Maternité** : 3 auges acier ou ciment armé (100×30 cm) — **30 000 × 3 = 90 000**\n- **Gestation** : auge collective 2-3 m linéaires — **80 000**\n- **Engraissement** : 3-5 auges collectives — **120 000**\n\n### Abreuvoirs tétine\n- 12 tétines acier inox (1/case) × 8 000 = **96 000 FCFA**\n- Tuyauterie PVC + collier = **30 000**\n\n## Maternité\n\n### Lampes chauffantes\n- 3 lampes infrarouge 250 W avec garde + suspension : **45 000 × 3 = 135 000**\n- Câbles + interrupteurs : **20 000**\n\n### Cages mise-bas (optionnel)\n- 3 cages truie + nid porcelets : **150 000 × 3 = 450 000**\n- (Ou alternative : box paillé sans cage, économique mais plus de pertes par écrasement)\n\n## Outillage\n\n### Mesure et soins\n- **Balance pèse-animaux** (jusqu''à 200 kg) : **80 000-150 000**\n- **Thermomètre rectal** : **5 000**\n- **Aiguilles + seringues** : **15 000**\n- **Pince castration / dents** : **15 000**\n- **Cathéters IA** (10) : **20 000**\n- **Pince Marteau identification** : **15 000**\n\n### Hygiène et entretien\n- **Pulvérisateur 5L** : **15 000**\n- **Brouette** : **30 000**\n- **Pelle, brosses, balais** : **20 000**\n- **Seaux, bidons** : **15 000**\n- **Bottes (3 paires)** : **45 000**\n- **Combinaisons de travail (3)** : **30 000**\n\n## Stockage et réfrigération\n\n- **Réfrigérateur** (vaccins, médicaments) : **150 000**\n- **Glacière transport** : **20 000**\n- **Étagères stockage aliment** : **40 000**\n- **Bidons stockage 200L** (eau, désinfectant) : **60 000**\n\n## Trousse de premiers soins\n\n- Antiseptiques (iode, betadine) : 15 000\n- Anti-inflammatoires (méloxicam, kétoprofène) : 30 000\n- Antibiotiques de base (amox, pénicilline) : 40 000\n- Fer dextran pour porcelets : 20 000\n- Vermifuges (ivermectine) : 25 000\n- Pansements, alcool, gants : 15 000\n- **Sous-total : 145 000**\n\n## TOTAL équipement de base\n\n**~ 750 000 - 1 000 000 FCFA** (sans cages mise-bas premium)\n\n## Priorisation si budget serré\n\n1. **Indispensable** : abreuvoirs, auges, lampes maternité, balance, trousse soin → 500 000\n2. **Très utile** : pulvérisateur, brouette, bottes → 100 000\n3. **Confort** : cages mise-bas, réfrigérateur → 600 000\n\n## Économies\n\n- **Auges ciment armé** fait-maison : -40% vs acier\n- **Lampes IR locales** : 2 000-5 000 FCFA mais durée vie faible\n- **Achat groupé** entre fermes : -10-15%\n- **Second main** sur fermes en cessation',
 ARRAY['equipement', 'budget', 'demarrage', 'liste'],
 'BIPORC, IFIP'),

('lutte-rongeurs-ferme', 'Lutte contre les rongeurs',
 'installation', 'intermediaire',
 'Rongeurs = vecteurs PPA, leptospirose, gaspillage aliment 5-15%. Stratégie : prévention construction + pièges + appâts sécurisés.',
 E'## Pourquoi c''est critique\n\n- **Vecteurs maladies** : leptospirose (avortements), salmonellose, PPA potentielle\n- **Gaspillage aliment** : 1 rat consomme 30-50 g/jour + contamine 10x ce qu''il consomme\n- **Dégâts** : câbles électriques rongés, isolation, sacs aliment percés\n- **100 rats × 50 g × 365 j = 1,8 t aliment perdu/an = 600 000 FCFA**\n\n## Prévention (construction)\n\n1. **Béton de sol** sans fissures\n2. **Bouchage** des trous murs (ciment + verre cassé)\n3. **Grilles 1 cm** sur toutes ouvertures (aération)\n4. **Hauteur minimale** : pas d''abris sous bâtiments\n5. **Stockage aliment surélevé** (50 cm sol) ET fermé\n6. **Pas de déchets** stagnants autour\n\n## Pièges mécaniques (recommandé)\n\n- **Tapettes classiques** : efficaces et économiques (1 000 FCFA/pièce)\n- **Pièges-cages** (vivants) : utiles pour identification espèce\n- **Pièges électriques** : 30-80 000 FCFA, efficaces mais cher\n- **Disposition** : le long des murs, près des entrées, sous palettes\n\n## Appâts (à utiliser avec précaution)\n\n### Boîtes appâts sécurisées\n- **Indispensable** : accès rats seulement, pas porcs ni enfants\n- Coût : 5-15 000 FCFA/boîte\n- Disposer : 1 boîte / 50 m²\n\n### Anticoagulants (raticides)\n- **Bromadiolone, brodifacoum, difenacoum**\n- Action lente (3-7 jours) = rats ne se méfient pas\n- **Tox secondaire** : éviter rats morts mangés par chiens/chats\n\n### Alternative naturelle\n- **Chats** : très efficaces mais nécessitent gestion\n- **Chouettes** : nichoirs encourageant (mais coexistence avec porcherie ?)\n\n## Programme intégré (efficacité max)\n\n1. **Prévention construction** = base\n2. **Hygiène stockage** aliment\n3. **Inspection hebdomadaire** : crottes, traces, sacs percés\n4. **Pièges en permanence** (10-20 pièces selon taille ferme)\n5. **Appâts en complément** si infestation visible\n6. **Suivi mensuel** : noter captures, ajuster\n\n## Erreurs\n\n- **Appâts en libre accès** : danger porcs/humains\n- **Pas de prévention** : pièges seuls = bataille perdue\n- **Aliment ouvert** : invitation permanente',
 ARRAY['rongeurs', 'rats', 'biosecurite', 'aliment'],
 'FAO, ANSES, IFIP'),

('gestion-fumier-compostage', 'Gestion fumier et compostage',
 'installation', 'intermediaire',
 'Fumier porc = ressource (vente maraîchers 500-1500 FCFA/sac) ou compostage. Évacuation hebdo, fosse étanche, valorisation possible.',
 E'## Production fumier ferme 10 truies\n\n- 10 truies × 5 kg fumier/j = 50 kg/j\n- + ~30 porcs en engraissement × 2 kg/j = 60 kg/j\n- **Total : ~110 kg/jour = 40 t/an**\n\n## Composition du fumier porcin\n\n- **N (azote)** : 8-12 kg/t\n- **P₂O₅ (phosphore)** : 6-9 kg/t\n- **K₂O (potassium)** : 4-7 kg/t\n- **Matière organique** : 25-35%\n\n→ **Excellent engrais** pour cultures maraîchères\n\n## Évacuation quotidienne\n\n1. **Brouette dédiée** (jamais utilisée pour aliment)\n2. **Pelle, fourche** pour décrasser\n3. **Vers zone stockage** éloignée bâtiment (15-30 m)\n4. **Fréquence** : quotidienne (raclage léger) + hebdomadaire (nettoyage approfondi)\n\n## Compostage (recommandé)\n\n### Composteur simple\n- Aire bétonnée 3×3 m + abri toit\n- Coût : 100-200 000 FCFA\n- Capacité : 5-10 m³ = 3-6 t fumier brut\n\n### Process compostage\n1. **Empilage** : alternance fumier + paille/copeaux (rapport C/N ~30)\n2. **Humidification** : poignée pressée = quelques gouttes\n3. **Retournement** : 1x/sem pendant 4-6 sem\n4. **Maturation** : 2-3 mois supplémentaires\n5. **Tamisage** : compost prêt = noir, odeur terreuse, texture friable\n\n### Bénéfices compost vs fumier brut\n- Moins de pathogènes (chaleur tue bactéries)\n- Meilleure manipulation (sec, sans odeur forte)\n- Plus concentré nutriments\n- Prix vente 2-3x plus élevé\n\n## Valorisation économique\n\n### Vente directe fumier brut\n- Maraîchers locaux : **500-1 000 FCFA/sac (50 kg)**\n- 40 t/an = 800 sacs = **400 000 - 800 000 FCFA**\n\n### Vente compost\n- **1 500-3 000 FCFA/sac (40 kg)**\n- 20 t compost/an = 500 sacs = **750 000 - 1,5 M FCFA**\n\n### Usage interne (potager ferme)\n- Maraîchage diversification revenus\n- Synergie agritech\n\n## Conformité environnementale\n\n- **Fosse étanche** obligatoire (pas de pollution nappe)\n- **Distance habitations** : 50-100 m\n- **Lagunage** pour effluents liquides si > 50 truies\n- **Pas d''épandage** par temps de pluie',
 ARRAY['fumier', 'compostage', 'engrais', 'valorisation'],
 'CIRAD, FAO, IFIP'),

('foncier-emplacement-ferme', 'Choisir l''emplacement de la ferme',
 'installation', 'expert',
 'Critères : foncier sécurisé, eau accessible, électricité, marché proche, distance habitations 100m+, terrain non inondable.',
 E'## Critères de choix (par ordre priorité)\n\n### 1. Foncier sécurisé\n- **Titre foncier** > certificat de propriété > permis occuper\n- **Éviter** : terres coutumières non documentées (conflits)\n- **Coût terrain** rural CI 2025 : 500 000 - 5 M / ha selon zone\n\n### 2. Accès eau\n- **Forage** possible (nappe < 50m) ou rivière permanente\n- 1 ferme 10 truies = **20-30 m³ eau/mois**\n- Coût forage : **800 000 - 2 M FCFA** selon profondeur\n\n### 3. Accès électricité\n- **Réseau CIE** à proximité (< 500 m) OU solaire viable\n- Si solaire : ensoleillement OK partout CI\n\n### 4. Proximité marché\n- **Distance acheteurs** (abattoirs, grossistes) : < 50 km idéal\n- Routes praticables toute l''année (saison pluies !)\n- Coût transport porcs vers abattoir : 5-15% prix vente\n\n### 5. Distance habitations\n- **Réglementation MIRAH** : 100 m minimum d''habitations\n- **Vent dominant** : porcherie en aval (odeurs)\n- Bonnes relations voisinage indispensables\n\n### 6. Topographie\n- **Terrain non inondable** (pas de bas-fonds saison pluies)\n- **Pente légère** 2-5% pour drainage\n- **Sol stable** (pas sablonneux qui s''affaisse)\n\n### 7. Environnement\n- **Pas de zone protégée** (parcs, réserves)\n- **Pas de zone marécageuse** (paludisme, moustiques)\n- **Climat** : pas de zones extrêmes\n\n## Zones favorables en CI\n\n### Zone forestière (Sud)\n- Pluviométrie : 1500-2000 mm/an\n- Eau abondante mais humidité élevée\n- Marchés Abidjan proches\n- ⚠️ Risque maladies parasitaires\n\n### Zone savane (Centre-Nord)\n- Pluviométrie : 800-1300 mm/an\n- Climat plus sec = moins de pathologies\n- Marchés Bouaké, Korhogo\n- ⚠️ Saison sèche = stress thermique\n\n### Zone côtière (Sud-Est)\n- Humidité forte, températures élevées\n- Très près Abidjan = marché premium\n- ⚠️ Coûts foncier élevés\n\n## Procédure acquisition foncière\n\n1. **Recherche** : agence ou démarchage direct\n2. **Visite** : visite + voisins consultation\n3. **Diagnostic juridique** : titre, conflits potentiels\n4. **Promesse de vente** + acompte\n5. **Acte notarié** + paiement\n6. **Immatriculation** au cadastre\n7. **Permis bâtir** mairie\n\n**Délais : 3-6 mois**, **Coût frais juridiques : 8-12% prix terrain**',
 ARRAY['foncier', 'emplacement', 'terrain', 'choix-site'],
 'MIRAH, MEMINADER, CEPICI'),

('erreurs-debutants-eviter', 'Top 10 erreurs débutants à éviter',
 'installation', 'debutant',
 'Erreurs fréquentes : sous-budget fonds roulement, achat trop d''animaux, bâtiments mal orientés, négliger sanitaire, pas de comptabilité.',
 E'## Les 10 erreurs qui coulent les fermes débutantes\n\n### 1. Sous-budgéter le fonds de roulement\n- **Erreur** : tout investir dans bâtiments + reproducteurs, oublier les 6 premiers mois sans revenus\n- **Conséquence** : famine porcs, arrêt brutal\n- **Solution** : prévoir 3-6 mois charges fonctionnement\n\n### 2. Acheter trop d''animaux d''un coup\n- **Erreur** : démarrer avec 30 truies sans expérience\n- **Conséquence** : maîtrise impossible, mortalités massives\n- **Solution** : commencer avec 5-10 truies, augmenter progressivement\n\n### 3. Bâtiments mal orientés / mal ventilés\n- **Erreur** : copier les plans européens (climat tempéré)\n- **Conséquence** : stress thermique chronique, GMQ chute\n- **Solution** : adaptation tropicale (cf tips conduite)\n\n### 4. Négliger la biosécurité dès le départ\n- **Erreur** : pas de sas, pas de quarantaine, visiteurs libres\n- **Conséquence** : maladies introduites, perte de cheptel\n- **Solution** : sas + clôture + protocole visiteurs dès J1\n\n### 5. Pas de carnet d''élevage\n- **Erreur** : "je me souviendrai"\n- **Conséquence** : pertes traçabilité, retards vaccination, erreurs gestion\n- **Solution** : carnet papier OU app dès première saillie\n\n### 6. Pas de comptabilité\n- **Erreur** : mélanger argent ferme et personnel\n- **Conséquence** : rentabilité inconnue, mauvaises décisions\n- **Solution** : compte bancaire dédié + Excel simple\n\n### 7. Mauvaise qualité génétique\n- **Erreur** : acheter "porcs du voisin" sans pedigree\n- **Conséquence** : GMQ médiocre, portées petites\n- **Solution** : reproducteurs certifiés MIRAH ou centres reconnus\n\n### 8. Aliment de mauvaise qualité (économies déplacées)\n- **Erreur** : sous-doser tourteau, utiliser maïs moisi\n- **Conséquence** : croissance lente, mortalités, IC catastrophique\n- **Solution** : qualité matières premières + formulation rigoureuse\n\n### 9. Pas d''écoute du vétérinaire\n- **Erreur** : auto-médication, ignorer signaux faibles\n- **Conséquence** : épidémies non gérées, antibiorésistance\n- **Solution** : véto référent + visites programmées\n\n### 10. Isolation professionnelle\n- **Erreur** : faire seul, pas de réseau\n- **Conséquence** : pas de partage expérience, pas de marché collectif\n- **Solution** : adhérer BIPORC, formations FIRCA, coopératives\n\n## Recommandations\n\n1. **Formation** : 3-6 mois apprentissage chez éleveur expérimenté avant démarrer\n2. **Mentor** : trouver un éleveur référent\n3. **Démarrer petit** : 5-10 truies max année 1\n4. **Mesurer tout** : pesées, conso, mortalités\n5. **Patience** : ROI moyen 4-6 ans, pas d''argent rapide',
 ARRAY['debutants', 'erreurs', 'conseils', 'demarrage'],
 'BIPORC, FAO, retours d''expérience CI');

-- Vérification finale
do $$
declare
  cnt int;
begin
  select count(*) into cnt from tips_conseiller;
  raise notice '✅ Tips conseiller V1 seedés : % tips', cnt;
end $$;
